//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/gestionacuerdo", ConfigurationName="SIACU.GestionAcuerdoIFI.GestionAcuerdoWSPortType")]
    public interface GestionAcuerdoWSPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación obtenerReintegroEquipo no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ws/postventa/gestionacuerdo/obtenerReintegroEquipo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerReintegroEquipoResponse1 obtenerReintegroEquipo(Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerReintegroEquipoRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación obtenerConsultaAcuerdo no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ws/postventa/gestionacuerdo/obtenerConsultaAcuerdo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerConsultaAcuerdoResponse1 obtenerConsultaAcuerdo(Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerConsultaAcuerdoRequest1 request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/postventa/gestionacuerdo/types")]
    public partial class obtenerReintegroEquipoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditRequestType auditRequestField;
        
        private string msisdnField;
        
        private string coIdField;
        
        private string fechaTransaccionField;
        
        private string cargoFijoNuevoField;
        
        private string motivoApadeceField;
        
        private string flagEquipoField;
        
        private parametrosTypeObjetoOpcional[] listaRequestOpcionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public auditRequestType auditRequest {
            get {
                return this.auditRequestField;
            }
            set {
                this.auditRequestField = value;
                this.RaisePropertyChanged("auditRequest");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
                this.RaisePropertyChanged("msisdn");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string coId {
            get {
                return this.coIdField;
            }
            set {
                this.coIdField = value;
                this.RaisePropertyChanged("coId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string fechaTransaccion {
            get {
                return this.fechaTransaccionField;
            }
            set {
                this.fechaTransaccionField = value;
                this.RaisePropertyChanged("fechaTransaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string cargoFijoNuevo {
            get {
                return this.cargoFijoNuevoField;
            }
            set {
                this.cargoFijoNuevoField = value;
                this.RaisePropertyChanged("cargoFijoNuevo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string motivoApadece {
            get {
                return this.motivoApadeceField;
            }
            set {
                this.motivoApadeceField = value;
                this.RaisePropertyChanged("motivoApadece");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string flagEquipo {
            get {
                return this.flagEquipoField;
            }
            set {
                this.flagEquipoField = value;
                this.RaisePropertyChanged("flagEquipo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaRequestOpcional {
            get {
                return this.listaRequestOpcionalField;
            }
            set {
                this.listaRequestOpcionalField = value;
                this.RaisePropertyChanged("listaRequestOpcional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public partial class auditRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string nombreAplicacionField;
        
        private string usuarioAplicacionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ipAplicacion {
            get {
                return this.ipAplicacionField;
            }
            set {
                this.ipAplicacionField = value;
                this.RaisePropertyChanged("ipAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nombreAplicacion {
            get {
                return this.nombreAplicacionField;
            }
            set {
                this.nombreAplicacionField = value;
                this.RaisePropertyChanged("nombreAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string usuarioAplicacion {
            get {
                return this.usuarioAplicacionField;
            }
            set {
                this.usuarioAplicacionField = value;
                this.RaisePropertyChanged("usuarioAplicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public partial class auditResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionField;
        
        private string codigoRespuestaField;
        
        private string mensajeRespuestaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("codigoRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
                this.RaisePropertyChanged("mensajeRespuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public partial class parametrosTypeObjetoOpcional : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string campoField;
        
        private string valorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string campo {
            get {
                return this.campoField;
            }
            set {
                this.campoField = value;
                this.RaisePropertyChanged("campo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/postventa/gestionacuerdo/types")]
    public partial class obtenerReintegroEquipoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditResponseType auditResponseField;
        
        private string acuerdoOrigenField;
        
        private string acuerdoIdField;
        
        private string coIdField;
        
        private string customerIdField;
        
        private string acuerdoEstadoField;
        
        private string acuerdoMontoApacedeTotalField;
        
        private string acuerdoVigenciaMesesField;
        
        private string acuerdoFechaInicioField;
        
        private string acuerdoFechaFinField;
        
        private string mesesAntiguedadField;
        
        private string mesesPendientesField;
        
        private string diasPendientesField;
        
        private string codPlazoAcuerdoField;
        
        private string descPlazoAcuerdoField;
        
        private string acuerdoCaducadoField;
        
        private string diasVigenciaField;
        
        private string descripcionEstadoAcuerdoField;
        
        private string montoApadeceField;
        
        private string cargoFijoDiarioField;
        
        private string precioListaField;
        
        private string precioVentaField;
        
        private string diasBloqueoField;
        
        private string finVigenciaRealField;
        
        private parametrosTypeObjetoOpcional[] listaResponseOpcionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public auditResponseType auditResponse {
            get {
                return this.auditResponseField;
            }
            set {
                this.auditResponseField = value;
                this.RaisePropertyChanged("auditResponse");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string acuerdoOrigen {
            get {
                return this.acuerdoOrigenField;
            }
            set {
                this.acuerdoOrigenField = value;
                this.RaisePropertyChanged("acuerdoOrigen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string acuerdoId {
            get {
                return this.acuerdoIdField;
            }
            set {
                this.acuerdoIdField = value;
                this.RaisePropertyChanged("acuerdoId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string coId {
            get {
                return this.coIdField;
            }
            set {
                this.coIdField = value;
                this.RaisePropertyChanged("coId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("customerId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string acuerdoEstado {
            get {
                return this.acuerdoEstadoField;
            }
            set {
                this.acuerdoEstadoField = value;
                this.RaisePropertyChanged("acuerdoEstado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string acuerdoMontoApacedeTotal {
            get {
                return this.acuerdoMontoApacedeTotalField;
            }
            set {
                this.acuerdoMontoApacedeTotalField = value;
                this.RaisePropertyChanged("acuerdoMontoApacedeTotal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string acuerdoVigenciaMeses {
            get {
                return this.acuerdoVigenciaMesesField;
            }
            set {
                this.acuerdoVigenciaMesesField = value;
                this.RaisePropertyChanged("acuerdoVigenciaMeses");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string acuerdoFechaInicio {
            get {
                return this.acuerdoFechaInicioField;
            }
            set {
                this.acuerdoFechaInicioField = value;
                this.RaisePropertyChanged("acuerdoFechaInicio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string acuerdoFechaFin {
            get {
                return this.acuerdoFechaFinField;
            }
            set {
                this.acuerdoFechaFinField = value;
                this.RaisePropertyChanged("acuerdoFechaFin");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string mesesAntiguedad {
            get {
                return this.mesesAntiguedadField;
            }
            set {
                this.mesesAntiguedadField = value;
                this.RaisePropertyChanged("mesesAntiguedad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string mesesPendientes {
            get {
                return this.mesesPendientesField;
            }
            set {
                this.mesesPendientesField = value;
                this.RaisePropertyChanged("mesesPendientes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string diasPendientes {
            get {
                return this.diasPendientesField;
            }
            set {
                this.diasPendientesField = value;
                this.RaisePropertyChanged("diasPendientes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string codPlazoAcuerdo {
            get {
                return this.codPlazoAcuerdoField;
            }
            set {
                this.codPlazoAcuerdoField = value;
                this.RaisePropertyChanged("codPlazoAcuerdo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string descPlazoAcuerdo {
            get {
                return this.descPlazoAcuerdoField;
            }
            set {
                this.descPlazoAcuerdoField = value;
                this.RaisePropertyChanged("descPlazoAcuerdo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string acuerdoCaducado {
            get {
                return this.acuerdoCaducadoField;
            }
            set {
                this.acuerdoCaducadoField = value;
                this.RaisePropertyChanged("acuerdoCaducado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string diasVigencia {
            get {
                return this.diasVigenciaField;
            }
            set {
                this.diasVigenciaField = value;
                this.RaisePropertyChanged("diasVigencia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string descripcionEstadoAcuerdo {
            get {
                return this.descripcionEstadoAcuerdoField;
            }
            set {
                this.descripcionEstadoAcuerdoField = value;
                this.RaisePropertyChanged("descripcionEstadoAcuerdo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string montoApadece {
            get {
                return this.montoApadeceField;
            }
            set {
                this.montoApadeceField = value;
                this.RaisePropertyChanged("montoApadece");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string cargoFijoDiario {
            get {
                return this.cargoFijoDiarioField;
            }
            set {
                this.cargoFijoDiarioField = value;
                this.RaisePropertyChanged("cargoFijoDiario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string precioLista {
            get {
                return this.precioListaField;
            }
            set {
                this.precioListaField = value;
                this.RaisePropertyChanged("precioLista");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string precioVenta {
            get {
                return this.precioVentaField;
            }
            set {
                this.precioVentaField = value;
                this.RaisePropertyChanged("precioVenta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string diasBloqueo {
            get {
                return this.diasBloqueoField;
            }
            set {
                this.diasBloqueoField = value;
                this.RaisePropertyChanged("diasBloqueo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string finVigenciaReal {
            get {
                return this.finVigenciaRealField;
            }
            set {
                this.finVigenciaRealField = value;
                this.RaisePropertyChanged("finVigenciaReal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=24)]
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaResponseOpcional {
            get {
                return this.listaResponseOpcionalField;
            }
            set {
                this.listaResponseOpcionalField = value;
                this.RaisePropertyChanged("listaResponseOpcional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerReintegroEquipoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/gestionacuerdo/types", Order=0)]
        public Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerReintegroEquipoRequest obtenerReintegroEquipoRequest;
        
        public obtenerReintegroEquipoRequest1() {
        }
        
        public obtenerReintegroEquipoRequest1(Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerReintegroEquipoRequest obtenerReintegroEquipoRequest) {
            this.obtenerReintegroEquipoRequest = obtenerReintegroEquipoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerReintegroEquipoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/gestionacuerdo/types", Order=0)]
        public Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerReintegroEquipoResponse obtenerReintegroEquipoResponse;
        
        public obtenerReintegroEquipoResponse1() {
        }
        
        public obtenerReintegroEquipoResponse1(Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerReintegroEquipoResponse obtenerReintegroEquipoResponse) {
            this.obtenerReintegroEquipoResponse = obtenerReintegroEquipoResponse;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/postventa/gestionacuerdo/types")]
    public partial class obtenerConsultaAcuerdoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditRequestType auditRequestField;
        
        private string valorField;
        
        private string tipoField;
        
        private parametrosTypeObjetoOpcional[] listaRequestOpcionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public auditRequestType auditRequest {
            get {
                return this.auditRequestField;
            }
            set {
                this.auditRequestField = value;
                this.RaisePropertyChanged("auditRequest");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaRequestOpcional {
            get {
                return this.listaRequestOpcionalField;
            }
            set {
                this.listaRequestOpcionalField = value;
                this.RaisePropertyChanged("listaRequestOpcional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/postventa/gestionacuerdo/types")]
    public partial class obtenerConsultaAcuerdoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditResponseType auditResponseField;
        
        private acuerdoTypeAcuerdo[] listaAcuerdosResponseField;
        
        private parametrosTypeObjetoOpcional[] listaResponseOpcionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public auditResponseType auditResponse {
            get {
                return this.auditResponseField;
            }
            set {
                this.auditResponseField = value;
                this.RaisePropertyChanged("auditResponse");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("acuerdo", IsNullable=false)]
        public acuerdoTypeAcuerdo[] listaAcuerdosResponse {
            get {
                return this.listaAcuerdosResponseField;
            }
            set {
                this.listaAcuerdosResponseField = value;
                this.RaisePropertyChanged("listaAcuerdosResponse");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaResponseOpcional {
            get {
                return this.listaResponseOpcionalField;
            }
            set {
                this.listaResponseOpcionalField = value;
                this.RaisePropertyChanged("listaResponseOpcional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/postventa/gestionacuerdo/types")]
    public partial class acuerdoTypeAcuerdo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string acuerdoIdField;
        
        private string coIdField;
        
        private string nroContratoField;
        
        private string customerIdField;
        
        private string custcodeField;
        
        private string numeroTelefonoField;
        
        private string tipoField;
        
        private string origenField;
        
        private string numeroPcsField;
        
        private string diasBloqSuspField;
        
        private string tipoPenalidadIdField;
        
        private string acuerdoPorField;
        
        private string fechaRenovacionField;
        
        private string fechaActivacionField;
        
        private string plazoAcuerdoField;
        
        private string finVigenciaIniField;
        
        private string finVigenciaRealField;
        
        private string estadoAcuerdoField;
        
        private string estadoAcuerdoDesField;
        
        private string estadoContratoField;
        
        private string estadoContratoDesField;
        
        private string tipoAcuerdoField;
        
        private string tipoAcuerdoDesField;
        
        private string tmcodeField;
        
        private string codPlazoAcuerdoField;
        
        private string flagRenovacionEquipoField;
        
        private string flagReposicionField;
        
        private string fechaContratoField;
        
        private string nombreClienteField;
        
        private string razonSocialField;
        
        private string direccionField;
        
        private string desCampanaField;
        
        private string precioListaField;
        
        private string precioLista6MesesField;
        
        private string codEquipoField;
        
        private string precioVentaField;
        
        private string precioVenta6MesesField;
        
        private string desPlanTarifField;
        
        private string montoPenalidadField;
        
        private string fechaFinAcuerdoField;
        
        private string fechaBloqSuspField;
        
        private string flagApadeceField;
        
        private string flagExigibleField;
        
        private string diasExigibleField;
        
        private string flagExigibleDesField;
        
        private string nroFacturasField;
        
        private string montoApadeceAnteriorField;
        
        private string pagoPenalidadField;
        
        private string flagPenalidadOrigenField;
        
        private string vigenciaMesesField;
        
        private string totalField;
        
        private string fechaFinField;
        
        private string origenAcuerdoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string acuerdoId {
            get {
                return this.acuerdoIdField;
            }
            set {
                this.acuerdoIdField = value;
                this.RaisePropertyChanged("acuerdoId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string coId {
            get {
                return this.coIdField;
            }
            set {
                this.coIdField = value;
                this.RaisePropertyChanged("coId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nroContrato {
            get {
                return this.nroContratoField;
            }
            set {
                this.nroContratoField = value;
                this.RaisePropertyChanged("nroContrato");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("customerId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string custcode {
            get {
                return this.custcodeField;
            }
            set {
                this.custcodeField = value;
                this.RaisePropertyChanged("custcode");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string numeroTelefono {
            get {
                return this.numeroTelefonoField;
            }
            set {
                this.numeroTelefonoField = value;
                this.RaisePropertyChanged("numeroTelefono");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string origen {
            get {
                return this.origenField;
            }
            set {
                this.origenField = value;
                this.RaisePropertyChanged("origen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string numeroPcs {
            get {
                return this.numeroPcsField;
            }
            set {
                this.numeroPcsField = value;
                this.RaisePropertyChanged("numeroPcs");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string diasBloqSusp {
            get {
                return this.diasBloqSuspField;
            }
            set {
                this.diasBloqSuspField = value;
                this.RaisePropertyChanged("diasBloqSusp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tipoPenalidadId {
            get {
                return this.tipoPenalidadIdField;
            }
            set {
                this.tipoPenalidadIdField = value;
                this.RaisePropertyChanged("tipoPenalidadId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string acuerdoPor {
            get {
                return this.acuerdoPorField;
            }
            set {
                this.acuerdoPorField = value;
                this.RaisePropertyChanged("acuerdoPor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fechaRenovacion {
            get {
                return this.fechaRenovacionField;
            }
            set {
                this.fechaRenovacionField = value;
                this.RaisePropertyChanged("fechaRenovacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fechaActivacion {
            get {
                return this.fechaActivacionField;
            }
            set {
                this.fechaActivacionField = value;
                this.RaisePropertyChanged("fechaActivacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string plazoAcuerdo {
            get {
                return this.plazoAcuerdoField;
            }
            set {
                this.plazoAcuerdoField = value;
                this.RaisePropertyChanged("plazoAcuerdo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string finVigenciaIni {
            get {
                return this.finVigenciaIniField;
            }
            set {
                this.finVigenciaIniField = value;
                this.RaisePropertyChanged("finVigenciaIni");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string finVigenciaReal {
            get {
                return this.finVigenciaRealField;
            }
            set {
                this.finVigenciaRealField = value;
                this.RaisePropertyChanged("finVigenciaReal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string estadoAcuerdo {
            get {
                return this.estadoAcuerdoField;
            }
            set {
                this.estadoAcuerdoField = value;
                this.RaisePropertyChanged("estadoAcuerdo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string estadoAcuerdoDes {
            get {
                return this.estadoAcuerdoDesField;
            }
            set {
                this.estadoAcuerdoDesField = value;
                this.RaisePropertyChanged("estadoAcuerdoDes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string estadoContrato {
            get {
                return this.estadoContratoField;
            }
            set {
                this.estadoContratoField = value;
                this.RaisePropertyChanged("estadoContrato");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string estadoContratoDes {
            get {
                return this.estadoContratoDesField;
            }
            set {
                this.estadoContratoDesField = value;
                this.RaisePropertyChanged("estadoContratoDes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tipoAcuerdo {
            get {
                return this.tipoAcuerdoField;
            }
            set {
                this.tipoAcuerdoField = value;
                this.RaisePropertyChanged("tipoAcuerdo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tipoAcuerdoDes {
            get {
                return this.tipoAcuerdoDesField;
            }
            set {
                this.tipoAcuerdoDesField = value;
                this.RaisePropertyChanged("tipoAcuerdoDes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tmcode {
            get {
                return this.tmcodeField;
            }
            set {
                this.tmcodeField = value;
                this.RaisePropertyChanged("tmcode");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codPlazoAcuerdo {
            get {
                return this.codPlazoAcuerdoField;
            }
            set {
                this.codPlazoAcuerdoField = value;
                this.RaisePropertyChanged("codPlazoAcuerdo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string flagRenovacionEquipo {
            get {
                return this.flagRenovacionEquipoField;
            }
            set {
                this.flagRenovacionEquipoField = value;
                this.RaisePropertyChanged("flagRenovacionEquipo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string flagReposicion {
            get {
                return this.flagReposicionField;
            }
            set {
                this.flagReposicionField = value;
                this.RaisePropertyChanged("flagReposicion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fechaContrato {
            get {
                return this.fechaContratoField;
            }
            set {
                this.fechaContratoField = value;
                this.RaisePropertyChanged("fechaContrato");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nombreCliente {
            get {
                return this.nombreClienteField;
            }
            set {
                this.nombreClienteField = value;
                this.RaisePropertyChanged("nombreCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
                this.RaisePropertyChanged("razonSocial");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string desCampana {
            get {
                return this.desCampanaField;
            }
            set {
                this.desCampanaField = value;
                this.RaisePropertyChanged("desCampana");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string precioLista {
            get {
                return this.precioListaField;
            }
            set {
                this.precioListaField = value;
                this.RaisePropertyChanged("precioLista");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string precioLista6Meses {
            get {
                return this.precioLista6MesesField;
            }
            set {
                this.precioLista6MesesField = value;
                this.RaisePropertyChanged("precioLista6Meses");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codEquipo {
            get {
                return this.codEquipoField;
            }
            set {
                this.codEquipoField = value;
                this.RaisePropertyChanged("codEquipo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string precioVenta {
            get {
                return this.precioVentaField;
            }
            set {
                this.precioVentaField = value;
                this.RaisePropertyChanged("precioVenta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string precioVenta6Meses {
            get {
                return this.precioVenta6MesesField;
            }
            set {
                this.precioVenta6MesesField = value;
                this.RaisePropertyChanged("precioVenta6Meses");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string desPlanTarif {
            get {
                return this.desPlanTarifField;
            }
            set {
                this.desPlanTarifField = value;
                this.RaisePropertyChanged("desPlanTarif");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string montoPenalidad {
            get {
                return this.montoPenalidadField;
            }
            set {
                this.montoPenalidadField = value;
                this.RaisePropertyChanged("montoPenalidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fechaFinAcuerdo {
            get {
                return this.fechaFinAcuerdoField;
            }
            set {
                this.fechaFinAcuerdoField = value;
                this.RaisePropertyChanged("fechaFinAcuerdo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fechaBloqSusp {
            get {
                return this.fechaBloqSuspField;
            }
            set {
                this.fechaBloqSuspField = value;
                this.RaisePropertyChanged("fechaBloqSusp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string flagApadece {
            get {
                return this.flagApadeceField;
            }
            set {
                this.flagApadeceField = value;
                this.RaisePropertyChanged("flagApadece");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string flagExigible {
            get {
                return this.flagExigibleField;
            }
            set {
                this.flagExigibleField = value;
                this.RaisePropertyChanged("flagExigible");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string diasExigible {
            get {
                return this.diasExigibleField;
            }
            set {
                this.diasExigibleField = value;
                this.RaisePropertyChanged("diasExigible");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string flagExigibleDes {
            get {
                return this.flagExigibleDesField;
            }
            set {
                this.flagExigibleDesField = value;
                this.RaisePropertyChanged("flagExigibleDes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nroFacturas {
            get {
                return this.nroFacturasField;
            }
            set {
                this.nroFacturasField = value;
                this.RaisePropertyChanged("nroFacturas");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string montoApadeceAnterior {
            get {
                return this.montoApadeceAnteriorField;
            }
            set {
                this.montoApadeceAnteriorField = value;
                this.RaisePropertyChanged("montoApadeceAnterior");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pagoPenalidad {
            get {
                return this.pagoPenalidadField;
            }
            set {
                this.pagoPenalidadField = value;
                this.RaisePropertyChanged("pagoPenalidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string flagPenalidadOrigen {
            get {
                return this.flagPenalidadOrigenField;
            }
            set {
                this.flagPenalidadOrigenField = value;
                this.RaisePropertyChanged("flagPenalidadOrigen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vigenciaMeses {
            get {
                return this.vigenciaMesesField;
            }
            set {
                this.vigenciaMesesField = value;
                this.RaisePropertyChanged("vigenciaMeses");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string origenAcuerdo {
            get {
                return this.origenAcuerdoField;
            }
            set {
                this.origenAcuerdoField = value;
                this.RaisePropertyChanged("origenAcuerdo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerConsultaAcuerdoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/gestionacuerdo/types", Order=0)]
        public Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerConsultaAcuerdoRequest obtenerConsultaAcuerdoRequest;
        
        public obtenerConsultaAcuerdoRequest1() {
        }
        
        public obtenerConsultaAcuerdoRequest1(Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerConsultaAcuerdoRequest obtenerConsultaAcuerdoRequest) {
            this.obtenerConsultaAcuerdoRequest = obtenerConsultaAcuerdoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerConsultaAcuerdoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/gestionacuerdo/types", Order=0)]
        public Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerConsultaAcuerdoResponse obtenerConsultaAcuerdoResponse;
        
        public obtenerConsultaAcuerdoResponse1() {
        }
        
        public obtenerConsultaAcuerdoResponse1(Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerConsultaAcuerdoResponse obtenerConsultaAcuerdoResponse) {
            this.obtenerConsultaAcuerdoResponse = obtenerConsultaAcuerdoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GestionAcuerdoWSPortTypeChannel : Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.GestionAcuerdoWSPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionAcuerdoWSPortTypeClient : System.ServiceModel.ClientBase<Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.GestionAcuerdoWSPortType>, Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.GestionAcuerdoWSPortType {
        
        public GestionAcuerdoWSPortTypeClient() {
        }
        
        public GestionAcuerdoWSPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionAcuerdoWSPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionAcuerdoWSPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionAcuerdoWSPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerReintegroEquipoResponse1 Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.GestionAcuerdoWSPortType.obtenerReintegroEquipo(Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerReintegroEquipoRequest1 request) {
            return base.Channel.obtenerReintegroEquipo(request);
        }
        
        public Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerReintegroEquipoResponse obtenerReintegroEquipo(Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerReintegroEquipoRequest obtenerReintegroEquipoRequest) {
            Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerReintegroEquipoRequest1 inValue = new Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerReintegroEquipoRequest1();
            inValue.obtenerReintegroEquipoRequest = obtenerReintegroEquipoRequest;
            Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerReintegroEquipoResponse1 retVal = ((Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.GestionAcuerdoWSPortType)(this)).obtenerReintegroEquipo(inValue);
            return retVal.obtenerReintegroEquipoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerConsultaAcuerdoResponse1 Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.GestionAcuerdoWSPortType.obtenerConsultaAcuerdo(Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerConsultaAcuerdoRequest1 request) {
            return base.Channel.obtenerConsultaAcuerdo(request);
        }
        
        public Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerConsultaAcuerdoResponse obtenerConsultaAcuerdo(Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerConsultaAcuerdoRequest obtenerConsultaAcuerdoRequest) {
            Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerConsultaAcuerdoRequest1 inValue = new Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerConsultaAcuerdoRequest1();
            inValue.obtenerConsultaAcuerdoRequest = obtenerConsultaAcuerdoRequest;
            Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.obtenerConsultaAcuerdoResponse1 retVal = ((Claro.SIACU.ProxyService.IFI.SIACU.GestionAcuerdoIFI.GestionAcuerdoWSPortType)(this)).obtenerConsultaAcuerdo(inValue);
            return retVal.obtenerConsultaAcuerdoResponse;
        }
    }
}
