

Session.OPTIONREDIRECT = "";
Session.ORIGINAPP = "";
Session.SEARCHTYPE = "";
Session.IDINSTANT = {};
Session.DESCRIPTIONINSTANT = {};
Session.DATACUSTOMER = {};
Session.CUSTOMERPRODUCT = {};
Session.DATASERVICE = {};
Session.HistoricalTriationRFA = {};
Session.DetalleHistoricalTriationRFA = {};
Session.MENU = {};
Session.ORIGINTYPE = {};
Session.CUSTOMEROLD = {};
Session.MESSAGEPREPAID = {};
Session.TELEPHONE = "982058891";
Session.SHOWPOPUPCUSTOMEROLD = {}
Session.SHOWDATACUSTOMERPREPAID = {}
Session.IDSESSION = "251232481611275";
Session.TypeMenuInst = "";
Session.ArchivoIntantanea = "";
Session.NewArchivoIntantanea = "";
Session.ListMassiveInstantFail = [];
Session.ListMassiveInstantCorrect = [];

Session.RouteSiteStart = "http://localhost:37738/";
Session.RouteSiteSiacpo = "http://limappdesv01/siacpost_p7/siacpo_inicio.htm";
Session.MsgInfoLine = "";
Session.CadenaPlanesRestringidosParaConsulta = "";
Session.DatosLinea = {};

/*INI - Sesiones en duro de Redireccionamiento*/
Session.PAGEACCESS = "ACP_CCF,ACP_COA,ACP_CHR,ACP_DMC,ACP_RVM,ACP_NRCP,ACP_EDI,ACP_RBO,ACP_DECB,ACP_EMD,ACP_CTD,ACP_EPS,ACP_PROT,ACP_BDI,ADT_SRV,ACP_DCR,ACP_BCCR,ACP_ARW847,ACP_ERW847,ACP_EPW847,ACP_ECW847,ACP_THFC,ACP_DCQ,ACP_AIA,ACP_DLCB,ACP_BNR,ACP_BICCID,ACP_GLC,ACP_DDC,ACP_DESON,ACP_RECANC,ACP_BUTELE,ACP_BUCUEN,ACP_BUNUSE,NO_BIOMETR,ACP_PRI,ACP_CSE,ACP_FRA,ACP_CMD,ACP_VTD,ACP_DCC,ACP_DEM,ACP_ARC,ACP_TVP,ACP_CDI,ACP_ADL,ACP_BELI,ACP_RAO,ACP_BPRO,ACP_BDSC,ACP_ETC,ACP_ADPP,ACP_ATD,ACP_COCT,ACP_BTE,ACP_CAP,ACP_MPF,ACP_MASW,ACP_OTL,ACP_EBDP,ACP_EDPM,ACP_ACDO,ACP_CCW847,ACP_CTS,ACP_DBQ,ACP_GNICH,ACP_BUNOMB,TVS_BNR,ACP_ORDT,ACP_CHL,ACP_LC,ACP_GAR,ACP_CRP,ACP_CCS,ACP_ECE,ACP_ECA,ACP_DLN,ACP_ALI,ACP_PPB,ACP_AFM,ACP_DCA,ACP_LKHR,COB_EDL,ACP_ETD,ACP_TSTV,ACP_111,ACP_RTI,ACP_RADI,ACP_SNCT,ACP_BRS,ACP_MFA,ACP_MFP,ACP_IPW,ACP_OTR,APC_ICR,ACP_RCB,ACP_CDOA,ACP_CSEG,ACP_EXW847,ACP_AMCP,ACP_RLTCSC,ACP_CLICRE,ACP_ADDL,ACP_GAPN,ACP_TIO,ACP_BNS,ADT_BTN,TVS_BDI,ACP_DIT,ACP_LMC,ACP_CTL,ACP_CPA,ACP_FIN,ACP_CTT,ACP_CTM,ACP_CVF,ACP_PCP,ACP_TCI,ACP_DEQ,ACP_RDL,ACP_MVM,ACP_DAR,ACP_BDM,ACP_VFP,ACP_DEAS,ACP_DECB,ACP_AMD,ACP_ZM,ABC_XY,ACP_TSRV,ACP_TTD,ACP_OVM,ACP_RLD,ACP_CDFT,ACP_APD,ACP_AVIP,ACP_AFPE,ACP_PMAT,ACP_RMW,ACP_MCC,ACP_IRW,ACP_SIM,ACP_ACCR,ACP_FPCT,ACP_CRW847,ACP_IMR,ACP_BDT,ACP_ATE,ACP_USFP,ACP_OBCS,TVS_BCT,TVS_BCI,TVS_BICCID,ACP_DCT,ACP_TCT,ACP_CHS,ACP_CAT,ACP_CPP,ACP_CPE,ACP_BDL,ACP_CLD,ACP_PVC,ACP_DTA,ACP_VNS,ACP_ACT,ACP_RBX,ACP_RBR,ACP_DCAE,ACP_ADEE,ACP_DELI,ACP_HR,ACP_HBA,COB_IDL,ACP_DPRO,ACP_SFD,ACP_DSD,ACP_AFPP,ACP_TVNT,ACP_FPRT,ADT_TIP,ACP_APW,ACP_EPW,ACP_CRW,ACP_ERW,ACP_EXW,ACP_MRS,ACP_RGC,ACP_CBDP,ACP_FPC,ACP_ADSC,ACP_PRC,ACP_ADHL,ACP_DRE,ACP_ASEG,ACP_EXRCM,ACP_BUDOCI,ACP_ASIFC,ACP_DCL,ACP_BCL,ACP_CHP,ACP_CAE,ACP_CFT,ACP_CAA,ACP_CDN,ACP_PCD,ACP_DTO,ACP_ECD,ACP_ECF,ACP_DEP,ACP_AAS,ACP_ETR,ACP_RBL,ACP_RBD,ACP_VFA,ACP_ITPD,ACP_RRF,ACP_ECHR,ACP_DDSC,ACP_FAD,ACP_MTD,ACP_DSCB,ACP_BNO,ACP_PCC,ADT_ACCS,ACP_HDE,ACP_ACCS,ACP_BLC,ACP_ISHL,ACP_DED,ACP_ADA,ACP_RLCFP,ACP_BURASO,TVS_BNO,TVS_BRS,ACP_DLI,ACP_CNT,ACP_CAC,ACP_DCO,ACP_PEC,ACP_ECB,ACP_LVI,ACP_DGR,ACP_CVM,ACP_DMME,ACP_DAC,ACP_ECL,ACP_RCR,ACP_RBE,ACP_EXD,ACP_VFS,ACP_DLAS,ACP_BROB,ACP_MNZM,ACP_TMD,ACP_RTD,ACP_IEA,ACP_TSMV,ACP_ADED,ACP_RSF,ACP_RTE,ACP_CCVIP,ACP_ARW,ACP_CCW,ACP_ECW,ACP_PAC,ACP_PACD,ACP_ATF,ACP_RMC847,ACP_CRTV,SST_VCC,ACP_INGV,ACP_PVR,ACP_AA4G,ACP_GDI1,ACP_PERF,ACP_ASDL,ACP_AUCA,ACP_PBDE,ACP_DFA,ACP_CTR,ACP_CSA,ACP_CLL,ACP_ROB,ACP_CRO,ACP_PFP,ACP_CHA,ACP_ECC,ACP_CTC,ACP_CDL,ACP_CNC,ACP_AMC,ACP_ARA,ACP_DRCE,ACP_PFPM,ACP_EEL,ACP_IDL,ACP_RDI,ACP_RBI,ACP_VFC,ACP_SLD,ACP_CCT,ACP_BCT,ACP_UCR,ACP_CDBP,ACP_IRW847,ACP_IPW847,ACP_APW847,ACP_RLSNCT,ACP_CFP,ACP_AFIC,ACP_TCII,ACP_PVCO,ACP_SIC,ACP_HLIN,ACP_BCID,ACP_GLCR,ACP_PFCE,ACP_VBIO,ACP_STAT,ACP_TLLE,ACP_VBDE,SIACA_CAPA,SIACA_VB,";
Session.CODEPROFILE = "1,43,90,2,82,81";
Session.USERQUERY = "0";
Session.PORTABILITY = "";
Session.PORTABILITYRESPUESTA = "";
//Session.TYPESERVICE = "1";
Session.LOGIN = "C12640";
Session.FULLNAME = "";
Session.SERVISBAMBAF = "0";
Session.USERLOGIN = "";
Session.SERVDTH_MOVIL = "0";
Session.LOGINM = "C12640";
Session.BUSQINSTANT = "";

Session.DATACUSTOMER.NOTADIRECCION = "Referencia Av las Brisas 422";


Session.ACCION = "";
Session.ACTUALIZADATOS = "";
Session.ALTURAVENTANA = "460";
Session.ANCHOVENTANA = "980";
Session.CAE = "";
Session.CASOINTERACCIONID = "";
Session.CBOLOCALIDAD = "";
Session.CLASEID = "1095";
Session.CO_ID = "";
Session.CODCLIENTE = "";
Session.CODUSR = "";
Session.CODUSER = "1100";
Session.CONTACTOID = "";
Session.CONTRATOID = "";
Session.CP = "";
Session.CRITBUSQUEDA = "1";
Session.CU = "1100";
Session.CUSTOMERID = "";
Session.CUSTUMERID = "";
Session.DATOSCLIENTE = "";
Session.DETALLELLAMADAS = "";
Session.DTH = "";
Session.ESRETENCION = "";
Session.ESTADOFORM = "N";
Session.FLAG_TFI = "";
Session.FLAGCINTILLO = "";
Session.FLAGCLIENTEANTIGUO = "";
Session.FLAGESLINEAINACTIVA = "";
Session.FLAGRCEC = "";
Session.FLAGTFI = "";
Session.ID = "";
Session.IDCASO = "";
Session.INVOICENUMBER = "";
Session.LLAMADODESDEINDEX = "S";
Session.MIGRACION = "";
Session.MODE = "";
Session.NRODOC = "";
Session.NRODOCUMENTO = "";
Session.NROSOTEXTERNO = "";
Session.NROTELEFONO = "16359229";
Session.OP = "1";
Session.OPCION = "";
Session.ORIGEN = "";
Session.PERFILES = "";
Session.PSALDO = "";
Session.PSTRCASOPADREID = "";
Session.PSTRCODCLIENTE = "";
Session.PSTRCODCONTRATOID = "";
Session.PSTRCODCUSTOMERID = "";
Session.PSTRINTERACCIONID = "";
Session.PSTRNOTA = "";
Session.PSTRTELREFER = "R";
Session.PSTRTIPO = "P";
Session.PSTRTRANSACCIONORIGEN = "";
Session.SERVICIO = "";
Session.SOLOCONSULTA = "";
Session.STRCBOTIPOBUSQUEDAVAL = "";
Session.STRTELEFONOBUS = "";
Session.SUBCLASEID = "109503";
Session.TEL = "";
Session.TELEFONOREF = "";
Session.TIPOAPP = "";
Session.TIPOBLOQUEO = "";
Session.TIPOCASOINTERACCION = "2";
Session.TIPOCONTACTO = "P";
Session.TIPOCUSTOMERID = "";
Session.TIPODOC = "";
Session.TIPOFORM = "";
Session.TIPOID = "10";
Session.TIPOLTE = "";
Session.TIPOSERVI = "";
Session.TIPOSERVICIO = "";
Session.TIPOTELEFONO = "2";
Session.TIPOTX = "";
Session.TO = "";
Session.TRANSACCIONDOL = "";
Session.TXTEXTERNO = "";
Session.TXTTELEFONO = "";
Session.PlanRate = "";
Session.TIPO = "";
Session.NUMLOTE = "";
Session.CO = "";
Session.USERACCESS = { optionPermissions: '' };
Session.STRIPNUMBERTRI = '';

Session.NuevoPlanMigradoPost = {};
Session.PlanesMigracion = {};
Session.IsBloqAllowConfiguration = {};
Session.TRANSACCIONMIGRACIONPLAN = "";
Session.TRANSACCIONMIGRACIONPLANConfig = "";
Session.CORPORATIVOMIGRACIONPLAN = "";
Session.COMSUMERCONTROLMIGRACIONPLAN = "";
Session.CODTIPOCLIENTEMIGRACIONPLAN = "";
Session.FECHAAPLICACIONMIGRACIONPLAN = "";
Session.DatosLineasFlagPlataforma = "";
Session.DatosLineasTelefono = "";
Session.DatosLineaNroContrato = "";
Session.DatosClienteCOD_TIPO_CLIENTE = "";
Session.DATASERVICECicloFacturacion = "22";
Session.HidCorporativo = "";
Session.HidTopeConsumo = "";
Session.hidCodProd = "";
Session.hidCartaInfor = "";
Session.hidDescripProducto = "";
Session.hidPlanLocal = "";
Session.TMCODE = "";
Session.hidAccesoPagina = "ACP_CCF,ACP_COA,ACP_CHR,ACP_DMC,ACP_RVM,ACP_NRCP,ACP_EDI,ACP_RBO,ACP_DECB,ACP_EMD,ACP_CTD,ACP_EPS,ACP_PROT,ACP_BDI,ADT_SRV,ACP_DCR,ACP_BCCR,ACP_ARW847,ACP_ERW847,ACP_EPW847,ACP_ECW847,ACP_THFC,ACP_DCQ,ACP_AIA,ACP_DLCB,ACP_BNR,ACP_BICCID,ACP_GLC,ACP_DDC,ACP_DESON,ACP_RECANC,ACP_BUTELE,ACP_BUCUEN,ACP_BUNUSE,NO_BIOMETR,ACP_PRI,ACP_CSE,ACP_FRA,ACP_CMD,ACP_VTD,ACP_DCC,ACP_DEM,ACP_ARC,ACP_TVP,ACP_CDI,ACP_ADL,ACP_BELI,ACP_RAO,ACP_BPRO,ACP_BDSC,ACP_ETC,ACP_ADPP,ACP_ATD,ACP_COCT,ACP_BTE,ACP_CAP,ACP_MPF,ACP_MASW,ACP_OTL,ACP_EBDP,ACP_EDPM,ACP_ACDO,ACP_CCW847,ACP_CTS,ACP_DBQ,ACP_GNICH,ACP_BUNOMB,TVS_BNR,ACP_ORDT,ACP_CHL,ACP_LC,ACP_GAR,ACP_CRP,ACP_CCS,ACP_ECE,ACP_ECA,ACP_DLN,ACP_ALI,ACP_PPB,ACP_AFM,ACP_DCA,ACP_LKHR,COB_EDL,ACP_ETD,ACP_TSTV,ACP_111,ACP_RTI,ACP_RADI,ACP_SNCT,ACP_BRS,ACP_MFA,ACP_MFP,ACP_IPW,ACP_OTR,APC_ICR,ACP_RCB,ACP_CDOA,ACP_CSEG,ACP_EXW847,ACP_AMCP,ACP_RLTCSC,ACP_CLICRE,ACP_ADDL,ACP_GAPN,ACP_TIO,ACP_BNS,ADT_BTN,TVS_BDI,ACP_DIT,ACP_LMC,ACP_CTL,ACP_CPA,ACP_FIN,ACP_CTT,ACP_CTM,ACP_CVF,ACP_PCP,ACP_TCI,ACP_DEQ,ACP_RDL,ACP_MVM,ACP_DAR,ACP_BDM,ACP_VFP,ACP_DEAS,ACP_DECB,ACP_AMD,ACP_ZM,ABC_XY,ACP_TSRV,ACP_TTD,ACP_OVM,ACP_RLD,ACP_CDFT,ACP_APD,ACP_AVIP,ACP_AFPE,ACP_PMAT,ACP_RMW,ACP_MCC,ACP_IRW,ACP_SIM,ACP_ACCR,ACP_FPCT,ACP_CRW847,ACP_IMR,ACP_BDT,ACP_ATE,ACP_USFP,ACP_OBCS,TVS_BCT,TVS_BCI,TVS_BICCID,ACP_DCT,ACP_TCT,ACP_CHS,ACP_CAT,ACP_CPP,ACP_CPE,ACP_BDL,ACP_CLD,ACP_PVC,ACP_DTA,ACP_VNS,ACP_ACT,ACP_RBX,ACP_RBR,ACP_DCAE,ACP_ADEE,ACP_DELI,ACP_HR,ACP_HBA,COB_IDL,ACP_DPRO,ACP_SFD,ACP_DSD,ACP_AFPP,ACP_TVNT,ACP_FPRT,ADT_TIP,ACP_APW,ACP_EPW,ACP_CRW,ACP_ERW,ACP_EXW,ACP_MRS,ACP_RGC,ACP_CBDP,ACP_FPC,ACP_ADSC,ACP_PRC,ACP_ADHL,ACP_DRE,ACP_ASEG,ACP_EXRCM,ACP_BUDOCI,ACP_ASIFC,ACP_DCL,ACP_BCL,ACP_CHP,ACP_CAE,ACP_CFT,ACP_CAA,ACP_CDN,ACP_PCD,ACP_DTO,ACP_ECD,ACP_ECF,ACP_DEP,ACP_AAS,ACP_ETR,ACP_RBL,ACP_RBD,ACP_VFA,ACP_ITPD,ACP_RRF,ACP_ECHR,ACP_DDSC,ACP_FAD,ACP_MTD,ACP_DSCB,ACP_BNO,ACP_PCC,ADT_ACCS,ACP_HDE,ACP_ACCS,ACP_BLC,ACP_ISHL,ACP_DED,ACP_ADA,ACP_RLCFP,ACP_BURASO,TVS_BNO,TVS_BRS,ACP_DLI,ACP_CNT,ACP_CAC,ACP_DCO,ACP_PEC,ACP_ECB,ACP_LVI,ACP_DGR,ACP_CVM,ACP_DMME,ACP_DAC,ACP_ECL,ACP_RCR,ACP_RBE,ACP_EXD,ACP_VFS,ACP_DLAS,ACP_BROB,ACP_MNZM,ACP_TMD,ACP_RTD,ACP_IEA,ACP_TSMV,ACP_ADED,ACP_RSF,ACP_RTE,ACP_CCVIP,ACP_ARW,ACP_CCW,ACP_ECW,ACP_PAC,ACP_PACD,ACP_ATF,ACP_RMC847,ACP_CRTV,SST_VCC,ACP_INGV,ACP_PVR,ACP_AA4G,ACP_GDI1,ACP_PERF,ACP_ASDL,ACP_AUCA,ACP_PBDE,ACP_DFA,ACP_CTR,ACP_CSA,ACP_CLL,ACP_ROB,ACP_CRO,ACP_PFP,ACP_CHA,ACP_ECC,ACP_CTC,ACP_CDL,ACP_CNC,ACP_AMC,ACP_ARA,ACP_DRCE,ACP_PFPM,ACP_EEL,ACP_IDL,ACP_RDI,ACP_RBI,ACP_VFC,ACP_SLD,ACP_CCT,ACP_BCT,ACP_UCR,ACP_CDBP,ACP_IRW847,ACP_IPW847,ACP_APW847,ACP_RLSNCT,ACP_CFP,ACP_AFIC,ACP_TCII,ACP_PVCO,ACP_SIC,ACP_HLIN,ACP_BCID,ACP_GLCR,ACP_PFCE,ACP_VBIO,ACP_STAT,ACP_TLLE,ACP_VBDE,SIACA_CAPA,SIACA_VB,";//Modificar Roberto - Eliminar por la llave correcta
Session.hidCobroApadece = "112";
Session.PlanBAM = "";
Session.PlanTFI = "";
Session.TipoClienteAplicacion = "";
Session.codigoPlanTarifario = "12344";
Session.FlagFidelizacion = "";
Session.hidCargoFijoTotalPlan = "";
Session.hidDiferenciaMontoCF = "";
Session.hidAuditFechProg = "";
Session.hidAuditChckFideliza = "";
Session.hidAuditChckSinCosto = "";
Session.hidPorcentajeIgv = "";
Session.hidAccesoCheck = "";
Session.hidAccesoFechProg = "";
Session.hidAccesoTopeSinCosto = "";
Session.hidCodSerConsumoAdi = "";
Session.hidValidaTipoCliente = "";
Session.hidOpTopeConsOrd = "";
Session.hidOpTopeConsCod = "";
Session.hidOpTopeConsDesc = "";
Session.hidOpTopeCons5Soles = "";
Session.hidFlgAutomatico = "";
Session.hidFlgCincoSoles = "";
Session.hiFlgAdicionalTope = "";
Session.hidOpTopeCodAutomatico = "";
Session.CodPlanClaroConexionChip = "";
Session.hidApadecNoAplica = "";
Session.hidFormaPago = "";
Session.gConstMsjPlanClaroConexionChip = ""; 
Session.gCodCostoCero = "";
Session.CodPlanSinTopeConsAutorizacion = "";
Session.hidModalidad = "";
Session.hidFamilia = "";
Session.hidCodSerActuals = "";
Session.dblCargoFijoBase = 0;
Session.dblTotalCF = 0;
Session.email = "roberto_martinez_gc@hotmail.com";
Session.hidConsumerControl = "";
Session.hidCheckSinCostoFinal = "";
Session.hidTipoPlan = "";
Session.hidValorTotalNuevoPlan = ""; 
Session.hidValorTotalNuevoPlan2 = "";
Session.hidCodSerArmaPost = ""; 
Session.hidObtenerDatosGrilla = ""; 
Session.hidOCC = ""; 
Session.hidFormaPagoApadece = "";
Session.hidTotPenalPCS = "";
Session.hidCodMotivo = "";
Session.hidCodSubMotiv = "";
Session.hidDesMotivo = "";
Session.hidDesSubMotivo = "";
Session.hidTotalApadece = "";
Session.hidTotalPCS = ""; 
Session.hidchckApadeceNoAplica = "";
Session.hidFechaActual = "";
Session.hidFechaLimite = "";
Session.Fideliza = false;
Session.strConfigPlantaforma = "";

Session.StarMonth = "";
Session.EndYear = "";

Session.DATACUSTOMER.BusinessName = "04GZ0PEW6M OROZM9JLRT";
Session.DATACUSTOMER.ServiceTFI = "Colaborador Max 12";
Session.DATACUSTOMER.BillingCycle = "16";
Session.DATACUSTOMER.IDENTIFICATIONDOCUMENTLR = "SIN PLAZO / POR TIEMPO ILIMITADO";
Session.DATACUSTOMER.CreditLimit = "140.4";
Session.DATACUSTOMER.AccountStatus = "Activo";
Session.DATACUSTOMER.LegalAgent = "DIEGO ALONSO BERROS";
Session.DATACUSTOMER.DATEEXPIRATION = new Date().toLocaleDateString();
Session.DATACUSTOMER.LimitConsume = "Consumo Adicional Flexible";
Session.DATACUSTOMER.STOP = "S/. 0.00";
Session.DATACUSTOMER.TELEPHONE = "";
Session.DATACUSTOMER.CONTRACT = "5745264";


Session.DATACUSTOMER._APELLIDOS = "";
Session.DATACUSTOMER._FECHA_ACT = "8/31/2004";
Session.DATACUSTOMER._NOMBRE_COMPLETO = "";
Session.DATACUSTOMER._NOMBRES = "";
Session.DATACUSTOMER._objPostDataAccount = "Nothing";
Session.DATACUSTOMER.APELLIDOS = "I1I80Y7L0H";
Session.DATACUSTOMER.ASESOR = "";
Session.DATACUSTOMER.CALLE_FAC = "Nothing";
Session.DATACUSTOMER.CALLE_LEGAL = "Nothing";
Session.DATACUSTOMER.CANT_REG = "Nothing";
Session.DATACUSTOMER.CARGO = "NJ74FNJP8B";
Session.DATACUSTOMER.CICLO_FACTURACION = "20";
Session.DATACUSTOMER.CIUDAD = "Nothing";
Session.DATACUSTOMER.COD_CENTRO_POBLADO = "Nothing";
Session.DATACUSTOMER.COD_TIPO_CLIENTE = "Nothing";
Session.DATACUSTOMER.CODIGO_PLANO_FACT = "LMRC007";
Session.DATACUSTOMER.CODIGO_PLANO_INST = "LMRC007";
Session.DATACUSTOMER.CONSULTOR = "";
Session.DATACUSTOMER.CONTACTO_CLIENTE = "qwwqw";
Session.DATACUSTOMER.CONTRATO_ID = "5745264";
Session.DATACUSTOMER.CREDIT_SCORE = "p";
Session.DATACUSTOMER.CUENTA = "1.10097698";
Session.DATACUSTOMER.CUSTOMER_ID = "6236466";
Session.DATACUSTOMER.DEPARTAMENTO = "LIMA";
Session.DATACUSTOMER.DEPARTEMENTO_FAC = "LIMA";
Session.DATACUSTOMER.DEPARTEMENTO_LEGAL = "LIMA";
Session.DATACUSTOMER.DEPOSITO = "Nothing";
Session.DATACUSTOMER.DES_CENTRO_POBLADO = "Nothing";
Session.DATACUSTOMER.DIRECCION_DESPACHO = "5TCFZAO4K3";
Session.DATACUSTOMER.DISTRITO = "LA MOLINA";
Session.DATACUSTOMER.DISTRITO_FAC = "LA MOLINA";
Session.DATACUSTOMER.DISTRITO_LEGAL = "RIMAC";
Session.DATACUSTOMER.DNI_RUC = "22412131";
Session.DATACUSTOMER.DOMICILIO = "CA AV LAS TORRES 12 TO 1 INT 123";
Session.DATACUSTOMER.EMAIL = "condorfp@globalhitss.com";
Session.DATACUSTOMER.ESTADO_CIVIL = "Soltero (a)";
Session.DATACUSTOMER.ESTADO_CIVIL_ID = "1";
Session.DATACUSTOMER.ESTADO_CONTACTO = "Nothing";
Session.DATACUSTOMER.ESTADO_CONTRATO = "Nothing";
Session.DATACUSTOMER.ESTADO_CUENTA = "Desactivo";
Session.DATACUSTOMER.ESTADO_SITE = "Nothing";
Session.DATACUSTOMER.FAX = "3333";
Session.DATACUSTOMER.FECHA_ACT = "8/31/2004";
Session.DATACUSTOMER.FECHA_ACTSTRING = "31/08/2004  12:00:00 a.m.";
Session.DATACUSTOMER.FECHA_NAC = "27/05/1972  12:00:00 a.m.";
Session.DATACUSTOMER.FLAG_EMAIL = "Nothing";
Session.DATACUSTOMER.FLAG_REGISTRADO = "0";
Session.DATACUSTOMER.FORMA_PAGO = "CONTADO";
Session.DATACUSTOMER.FUNCION = "Nothing";
Session.DATACUSTOMER.LIMITE_CREDITO = "422";
Session.DATACUSTOMER.LUGAR_NACIMIENTO_DES = "Adserbeiyan";
Session.DATACUSTOMER.LUGAR_NACIMIENTO_ID = "15";
Session.DATACUSTOMER.MODALIDAD = "Nothing";
Session.DATACUSTOMER.MOTIVO_REGISTRO = "Nothing";
Session.DATACUSTOMER.NICHO = "";
Session.DATACUSTOMER.NOMBRE_COMERCIAL = "UI7UC2PMGJ";
Session.DATACUSTOMER.NOMBRE_COMPLETO = "DIEGO ALONSO BERROS";
Session.DATACUSTOMER.NOMBRES = "H7VWRBSWRF";
Session.DATACUSTOMER.NRO_DOC = "22412131";
Session.DATACUSTOMER.OBJID_CONTACTO = "268607725";
Session.DATACUSTOMER.OBJID_SITE = "Nothing";
Session.DATACUSTOMER.objPostDataAccount = "Nothing";
Session.DATACUSTOMER.OCUPACION = "Nothing";
Session.DATACUSTOMER.P_FLAG_CONSULTA = "Nothing";
Session.DATACUSTOMER.P_MSG_TEXT = "Nothing";
Session.DATACUSTOMER.PAIS_FAC = "Peru";
Session.DATACUSTOMER.PAIS_LEGAL = "peru";
Session.DATACUSTOMER.POSTAL_FAC = "";
Session.DATACUSTOMER.POSTAL_LEGAL = "";
Session.DATACUSTOMER.PROVINCIA = "LIMA";
Session.DATACUSTOMER.PROVINCIA_FAC = "LIMA";
Session.DATACUSTOMER.PROVINCIA_LEGAL = "LIMA";
Session.DATACUSTOMER.PUNTO_VENTA = "Nothing";
Session.DATACUSTOMER.RAZON_SOCIAL = "APWZ2T1NB2";
Session.DATACUSTOMER.REFERENCIA = "ASO 123 SEC 1 ZONA FRENTE METRO";
Session.DATACUSTOMER.RENTA = "Nothing";
Session.DATACUSTOMER.REPRESENTANTE_LEGAL = "RNG1EAPAAM";
Session.DATACUSTOMER.RESPONSABLE_PAGO = "X";
Session.DATACUSTOMER.ROL_CONTACTO = "Nothing";
Session.DATACUSTOMER.S_APELLIDOS = "Nothing";
Session.DATACUSTOMER.S_NOMBRES = "Nothing";
Session.DATACUSTOMER.SEGMENTO = "Medio";
Session.DATACUSTOMER.SEXO = "f";
Session.DATACUSTOMER.TELEF_REFERENCIA = "429285";
Session.DATACUSTOMER.TELEFONO = "429285";
Session.DATACUSTOMER.TELEFONO_CONTACTO = "963963963";
Session.DATACUSTOMER.TEXTO_NOTAS = "Nothing";
Session.DATACUSTOMER.TIPO_CLIENTE = "Consumer";
Session.DATACUSTOMER.TIPO_DOC = "DNI";
Session.DATACUSTOMER.TIPO_PRODUCTO = "Nothing";
Session.DATACUSTOMER.TIPO_SERVICIO = "Nothing";
Session.DATACUSTOMER.TOTAL_CUENTAS = "Nothing";
Session.DATACUSTOMER.TOTAL_LINEAS = "Nothing";
Session.DATACUSTOMER.UBIGEO_FACT = "150128";
Session.DATACUSTOMER.UBIGEO_INST = "150128";
Session.DATACUSTOMER.URBANIZACION = "Nothing";
Session.DATACUSTOMER.URBANIZACION_FAC = "ASO 123 SEC 1 ZONA FRENTE METRO";
Session.DATACUSTOMER.URBANIZACION_LEGAL = "BW4ULDBVXZ";
Session.DATACUSTOMER.USUARIO = "Nothing";
Session.DATACUSTOMER.ZIPCODE = "Nothing";

/*FIN - Parametro de Change Type Customer*/




/*SESSION DE DATOS EN LINEA*/
Session.DATLINE = {};
Session.DATLINE._Fecha_Estado = "12:00:00 AM";
Session.DATLINE.cableTv = "T";
Session.DATLINE.Cambiado_Por = "Nothing";
Session.DATLINE.CambiosTarifaGratis = "Nothing";
Session.DATLINE.CambiosTriosGratis = "Nothing";
Session.DATLINE.Campana = "";
Session.DATLINE.CNTNumber = "Nothing";
Session.DATLINE.Cod_Plan_Tarifario = "1435";
Session.DATLINE.coId = "";
Session.DATLINE.ContratoID = "Nothing";
Session.DATLINE.EsLTE = "False";
Session.DATLINE.Estado_Acuerdo = "Nothing";
Session.DATLINE.FecActivacion = "11/12/2014  07:41:52 p.m.";
Session.DATLINE.FecDol = "Nothing";
Session.DATLINE.FecExpLinea = "Nothing";
Session.DATLINE.Fecha_Estado = "12:00:00 AM";
Session.DATLINE.Fecha_Estado_Str = "01/01/0001 12:00:00 a.m.";
Session.DATLINE.Fecha_Fin_Acuerdo = "Nothing";
Session.DATLINE.fechaEstado = "15/02/2017  05:09:38 p.m.";
Session.DATLINE.FechaExpiracionSaldo = "Nothing";
Session.DATLINE.Flag_Plataforma = "T";
Session.DATLINE.Flag_TFI = "Nothing";
Session.DATLINE.internet = "F";
Session.DATLINE.Introducido_El = "12:00:00 AM";
Session.DATLINE.Introducido_Por = "Nothing";
Session.DATLINE.IsCNTPossible = "Nothing";
Session.DATLINE.Motivo = "Activación";
Session.DATLINE.msisdn = "16489257";
Session.DATLINE.NoEs3Play = "Nothing";
Session.DATLINE.NroCelular = "Nothing";
Session.DATLINE.NroFamAmigos = "Nothing";
Session.DATLINE.NroICCID = "Nothing";
Session.DATLINE.NroIMSI = "Nothing";
Session.DATLINE.PIN1 = "Nothing";
Session.DATLINE.PIN2 = "Nothing";
Session.DATLINE.Plan = "Plan 2 Play Cable -Telefono";
Session.DATLINE.PlanTarifario = "Nothing";
Session.DATLINE.Plazo_Contrato = "";
Session.DATLINE.ProviderID = "Nothing";
Session.DATLINE.ptoVenta = "";
Session.DATLINE.PUK1 = "Nothing";
Session.DATLINE.PUK2 = "Nothing";
Session.DATLINE.SaldoPrincipal = "Nothing";
Session.DATLINE.StatusIMSI = "Nothing";
Session.DATLINE.StatusLinea = "Activo";
Session.DATLINE.SubscriberStatus = "Nothing";
Session.DATLINE.telefonia = "T";
Session.DATLINE.tipoProducto = "Nothing";
Session.DATLINE.tipoServicio = "Nothing";
Session.DATLINE.TipoTriacion = "Nothing";
Session.DATLINE.Valido_Desde = "12:00:00 AM";
Session.DATLINE.Vendedor = "";
/*FIN SESSION DE DATOS EN LINEA*/


/*USUARIO DE SESSION*/
Session.USERACCESS = {};
Session.USERACCESS.ACCESOCARGACONTRATO = "";
Session.USERACCESS.ACCESOPORFILTRO = "Nothing";
Session.USERACCESS.ACCESOPORFILTROFLAG = "2";
Session.USERACCESS.AREADESSCRIPTION = "Sistemas Post Venta";
Session.USERACCESS.AREAID = "421";
Session.USERACCESS.CADENAOPTION = "HFC_PRI,HFC_DIT,HFC_DLI,HFC_RFA,HFC_CPA,HFC_CTR,HFC_PCD,HFC_ECC,HFC_ARC,HFC_IDL,HFC_RBE,HFC_CDFT,HFC_ZM,HFC_DCL,HFC_CHS,HFC_ECF,HFC_CMD,HFC_TRI,HFC_AIMP,HFC_SFDD,HFC_RSOT,HFC_ADA,HFC_COB,HFC_MOB,HFC_CMS,HFC_BUCINT,LTE_ADDI,LTE_IDL,LTE_ECE1,LTE_ECC,LTE_NIMP,LTE_GRCS,LTE_AFP,HFC_LSVO,LTE_GCDC,HFC_AMC,HFC_CSE,HFC_CLL,HFC_COA,HFC_RCT,HFC_PPB,HFC_DAC,HFC_RBI,HFC_BTE,HFC_MNZM,HFC_PCC,HFC_CHP,HFC_ARA,HFC_DCO,HFC_SNCP,HFC_VNSD,HFC_RTCA,HFC_RTED,HFC_BTP,HFC_ATP,HFC_FPTC,HFC_RGNF,HFC_CSNF,HFC_DEB,HFC_BUTELE,LTE_EEL,LTE_ARC,LTE_ATP,LTE_GADE,LTE_GPSR,LTE_GCDF,LTE_BCTP,LTE_BRS,LTE_CHLR,HFC_LCNT,HFC_CTER,HFC_DFA,HFC_CCF,HFC_CRO,HFC_ECE,HFC_ALI,HFC_DRCE,HFC_EEL,HFC_ECHR,HFC_EDI,HFC_AMD,HFC_BDI,HFC_BCT,HFC_ATD,HFC_CDBP,HFC_CTL,HFC_DIN,HFC_GABD,HFC_AFP,HFC_CVMD,CON_TI,HFC_COI,HFC_AUCA,HFC_BUCUEN,LTE_CNC,LTE_DRCE,LTE_GOVT,LTE_GADA,LTE_GCDM,LTE_GRCR,LTE_BCE,HFC_LDND,HFC_CRP,HFC_CTT,HFC_CTDC,HFC_TCT,HFC_CTM,HFC_CAA,HFC_CAE,HFC_TCI,HFC_HDE,HFC_RPC,HFC_RBO,HFC_APD,HFC_DCT,HFC_CSA,HFC_AGS,HFC_NFMP,HFC_AFMP,HFC_SRTN,HFC_HCR,HFC_CRB,HFC_CRI,HFC_ELI,HFC_BURASO,LTE_RBI,LTE_RSOT,LTE_BTP,LTE_MPPF,LTE_AIMP,LTE_TSPL,HFC_LNBS,LTE_PCRF,HFC_CPP,HFC_CVF,HFC_BDM,HFC_HR,HFC_TSTV,HFC_RTD,HFC_ETD,HFC_EPS,HFC_TMD,HFC_PFP,HFC_RLN,HFC_CVSV,HFC_GCGS,HFC_MVMD,HFC_TCC,HFC_CCCT,HFC_MOI,HFC_EXT,HFC_CPH,HFC_BUNOMB,HFC_BUNDOC,HFC_BUCONT,LTE_FTIE,LTE_RTI,LTE_IMMP,LTE_GTI,LTE_GTE,LTE_GAMP,LTE_GSRS,LTE_RTCA,HFC_LTFO,HFC_LCNA,HFC_LRSL,HFC_JAM,HFC_RGC,HFC_CAC,HFC_CHL,HFC_CAT,HFC_PEC,HFC_RDI,HFC_ITPD,HFC_ECL,HFC_IEA,HFC_TTD,HFC_CTD,HFC_CFT,HFC_CCS,HFC_EMD,HFC_RCL,HFC_EMDT,HFC_IMMP,HFC_CDLD,HFC_FTIE,HFC_BCIN,HFC_CRPC,HFC_COT,HFC_CCFT,HFC_RECAC,HFC_BUCUST,LTE_CDL,LTE_ECE,LTE_ASOT,LTE_GAOC,LTE_GDF,LTE_GADI,HFC_BDL,HFC_CDN,HFC_CPE,HFC_CHR,HFC_VTD,HFC_BNO,HFC_TSMV,HFC_TSRV,HFC_RBR,HFC_NIMP,HFC_RVMD,HFC_ECCM,HFC_ASOT,HFC_CSTC,HFC_CRIM,HFC_COPP,LTE_TCC,LTE_BDM,LTE_CDFT,LTE_DIN,LTE_GIDA,LTE_GASA,LTE_GDLL,LTE_GBAO,LTE_GBRA,HFC_CLD,HFC_PCP,HFC_CHA,HFC_LVI,HFC_DTO,HFC_RBL,HFC_BRS,HFC_ECD,HFC_MTD,HFC_ACP,HFC_ADM,HFC_ADFP,HFC_MPPF,HFC_CST,HFC_BCO,HFC_BCID,LTE_CDEQ,LTE_HCR,LTE_RBE,LTE_RTE,LTE_NFMP,LTE_AFMP";
Session.USERACCESS.CADENAPERFIL = "2";
Session.USERACCESS.CANALVENTA = "Nothing";
Session.USERACCESS.CANALVENTADESCRIPTION = "Nothing";
Session.USERACCESS.CODEPERFIL = "2";
Session.USERACCESS.CODEUSER = "1100";
Session.USERACCESS.CODEUSERRED = "C12640";
Session.USERACCESS.CODEVENDEDORSAP = "Nothing";
Session.USERACCESS.STATEACCESS = "1";
Session.USERACCESS.HOST = "::1";
Session.USERACCESS.NAMECOMPLET = "SAMUEL SALOMON INGA BORJA";
Session.USERACCESS.OFFICEVENTA = "Nothing";
Session.USERACCESS.OFFICEVENTADESCRIPTION = "Nothing";
Session.USERACCESS.TERMINAR = "Nothing";
Session.USERACCESS.USERCONSULT = "0";
/*FIN DE USUARIO DE SESSION*/

/*HIDDEN*/
Session.HIDDEN = {};
Session.HIDDEN.hdnSiteUrl = "http://limappdesv01/siacpost_p7/siacpo_inicio.htm";
Session.HIDDEN.gstrUserHostName = "::1";
Session.HIDDEN.gstrLocalAddr = "::1";
Session.HIDDEN.hdnTipiGuardar = "TRANSACCION_DETALLE_LLAMADAS_HFC";
Session.HIDDEN.hdnTipiBuscar = "TRANSACCION_DETALLE_LLAMADAS_HFC_BUSCAR";
Session.HIDDEN.hidCodOpcion = "4434";
Session.HIDDEN.hidTransaccion = "TRANSACCION_DETALLE_LLAMADAS";
Session.DatosLinea.telefonia = "T";
/*FIN HIDDEN*/

Session.BilledCallsDetailHFC= {}
Session.BilledCallsDetailHFC.ListModels = {};
Session.hiddenMonthYearLimit = "";
var vTelefoniaMovil = "M";

Session.MESSAGEHFC = {};
Session.ENABLEDPERMISION = {};

function SetDataRedirect(Session) {

    Session.SUREDIRECT = Session.ORIGINTYPE;
    Session.TIPOAPP = "SGA";
    Session.INSTANTANEAID = Session.IDINSTANT;
    Session.TELEFONO = Session.TELEPHONE;
    Session.TELEFONOSAR = Session.TELEPHONE;
    Session.PSTRCUSTOMERID = Session.DATACUSTOMER.CustomerID;
    Session.CONTACTCODE = Session.DATACUSTOMER.ContactCode;
    if (Session.DATACUSTOMER.Segment2 == null)
    {
        Session.DATACUSTOMER.Segment2 = Session.DATACUSTOMER.Segment;
    }
      
    
    
    switch (Session.SEARCHTYPE) {
        case '1': Session.TIPOBUSQ = "3";
            break;
        case '2': Session.TIPOBUSQ = "4";
            break;
        case '3': Session.TIPOBUSQ = "2";
            break;
        case '4': Session.TIPOBUSQ = "7";
            break;
        default: Session.TIPOBUSQ = "";
    }
    if (Session.ORIGINTYPE == "POSTPAID") {
        Session.CUENTA = Session.DATACUSTOMER.Account;
        Session.CONTRATOID = Session.DATACUSTOMER.ContractID;
        Session.CUSTOMERID = Session.DATACUSTOMER.CustomerID;
        Session.OBJID = Session.DATACUSTOMER.IdContactObject;
    } else if (Session.ORIGINTYPE == "PREPAID") {
        Session.CUENTA = Session.DATACUSTOMER.SiteId;
        Session.OBJID = Session.DATACUSTOMER.CustomerCode;
    } 

    Session.ACCESSBLACKLIST = "1";
   };

Session.CODERESPONSEPREPAIDSERVICE = "";

Session.ORIGINTYPESERVICE = "";
Session.CONTRACTIDSERVICE = "";






Session.DATACUSTOMER.B_TELEPHONE = true;
Session.DATACUSTOMER.B_CABLE = true;
Session.DATACUSTOMER.B_INTERNET = false;



Session.IDENTIFICADORDESCIDEQUIPO = "";




Session.ServerDate = "";
Session.History = "";
Session.ValidateETA = "0";
Session.RequestActId = "";
Session.DateNew = "";
Session.CodUbigeo = "";
 
 
//INICIO-JEAN
Session.DatosDireccionMapa = "";
Session.DatosDireccionMapaTipoVia = "";
Session.DatosDireccionMapaNombreVia = "";
Session.DatosDireccionMapaNroVia = "";
Session.DatosDireccionMapaTipoSublocalidad = "";
Session.DatosDireccionMapaSublocalidad = "";
Session.DatosDireccionMapaDistrito = "";
//Session.DatosDireccionStandard = "";
Session.DatosDireccionMapaProvincia = "";
Session.DatosDireccionMapaDepartamento = "";
Session.DatosDireccionMapaPais = "";
Session.DatosDireccionMapaLat = "";
Session.DatosDireccionMapaLon = "";
Session.DatosDireccionMapaDirStd = "";
Session.DatosDireccionMapaCodPostal = "";
Session.DatosCompletoDirMapa = {};
//FIN-JEAN
 
