//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:pe.com.claro.siacpostpago.exceptions")]
    public partial class SIACPoException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pe/com/claro/siacpostpago/ws", ConfigurationName="SIACU.TriacionPostpagoWS.SIACPostpagoTxWS")]
    public interface SIACPostpagoTxWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://claro.com/SIACPostpago/DesbloqueaContratoResponse.xsd) no coincide con el valor predeterminado (http://pe/com/claro/siacpostpago/ws).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPoException), Action="", Name="SIACPoException", Namespace="java:pe.com.claro.siacpostpago.exceptions")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="bscs_DesbloqueaContratoResponse")]
        Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.DesbloquearContratoResponse DesbloquearContrato(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.DesbloquearContratoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.DesbloquearContratoResponse> DesbloquearContratoAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.DesbloquearContratoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://claro.com/SIACPostpago/listarTriaciones) no coincide con el valor predeterminado (http://pe/com/claro/siacpostpago/ws).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPoException), Action="", Name="SIACPoException", Namespace="java:pe.com.claro.siacpostpago.exceptions")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="listarTriacionesResponse")]
        Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTriacionesResponse1 listarTriaciones(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTriacionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTriacionesResponse1> listarTriacionesAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTriacionesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://claro.com/SIACPostpago/bscs_cambioNombreResponse.xsd) no coincide con el valor predeterminado (http://pe/com/claro/siacpostpago/ws).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPoException), Action="", Name="SIACPoException", Namespace="java:pe.com.claro.siacpostpago.exceptions")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="bscs_cambioNombreResponse")]
        Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioNombreResponse cambioNombre(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioNombreResponse> cambioNombreAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioNombreRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://claro.com/SIACPostpago/BloqueaContratoResponse) no coincide con el valor predeterminado (http://pe/com/claro/siacpostpago/ws).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPoException), Action="", Name="SIACPoException", Namespace="java:pe.com.claro.siacpostpago.exceptions")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="BloqueaContratoResponse")]
        Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloquearContratoResponse BloquearContrato(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloquearContratoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloquearContratoResponse> BloquearContratoAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloquearContratoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://claro.com/SIACPostpago/activaTriacion) no coincide con el valor predeterminado (http://pe/com/claro/siacpostpago/ws).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPoException), Action="", Name="SIACPoException", Namespace="java:pe.com.claro.siacpostpago.exceptions")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="activaTriacionResponse")]
        Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.ActivaTriacionResponse1 ActivaTriacion(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.ActivaTriacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.ActivaTriacionResponse1> ActivaTriacionAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.ActivaTriacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://claro.com/SIACPostpago/bscs_cambioDatosMenoresResponse.xsd) no coincide con el valor predeterminado (http://pe/com/claro/siacpostpago/ws).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPoException), Action="", Name="SIACPoException", Namespace="java:pe.com.claro.siacpostpago.exceptions")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="bscs_cambioDatosMenoresResponse")]
        Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.actualizaDatosMenoresResponse actualizaDatosMenores(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.actualizaDatosMenoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.actualizaDatosMenoresResponse> actualizaDatosMenoresAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.actualizaDatosMenoresRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://claro.com/SIACPostpago/activaTriacion) no coincide con el valor predeterminado (http://pe/com/claro/siacpostpago/ws).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPoException), Action="", Name="SIACPoException", Namespace="java:pe.com.claro.siacpostpago.exceptions")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="activaTriacionResponse")]
        Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.EjecutaTriacionResponse EjecutaTriacion(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.EjecutaTriacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.EjecutaTriacionResponse> EjecutaTriacionAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.EjecutaTriacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://claro.com/SIACPostpago/listarTicklers) no coincide con el valor predeterminado (http://pe/com/claro/siacpostpago/ws).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPoException), Action="", Name="SIACPoException", Namespace="java:pe.com.claro.siacpostpago.exceptions")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="listarTicklersResponse")]
        Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTicklersResponse1 listarTicklers(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTicklersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTicklersResponse1> listarTicklersAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTicklersRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://claro.com/SIACPostpago/bscs_cambioDireccionPostal_response.xsd) no coincide con el valor predeterminado (http://pe/com/claro/siacpostpago/ws).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPoException), Action="", Name="SIACPoException", Namespace="java:pe.com.claro.siacpostpago.exceptions")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="bscs_cambioDireccionPostal_response")]
        Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioDireccionPostalResponse cambioDireccionPostal(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioDireccionPostalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioDireccionPostalResponse> cambioDireccionPostalAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioDireccionPostalRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com/SIACPostpago/DesbloqueaContrato.xsd")]
    public partial class bscs_DesbloqueaContratoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int p_coidField;
        
        private string p_tickler_codeField;
        
        private string p_usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int p_coid {
            get {
                return this.p_coidField;
            }
            set {
                this.p_coidField = value;
                this.RaisePropertyChanged("p_coid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string p_tickler_code {
            get {
                return this.p_tickler_codeField;
            }
            set {
                this.p_tickler_codeField = value;
                this.RaisePropertyChanged("p_tickler_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string p_username {
            get {
                return this.p_usernameField;
            }
            set {
                this.p_usernameField = value;
                this.RaisePropertyChanged("p_username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com/SIACPostpago/DesbloqueaContratoResponse.xsd")]
    public partial class bscs_DesbloqueaContratoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int p_request_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int p_request_id {
            get {
                return this.p_request_idField;
            }
            set {
                this.p_request_idField = value;
                this.RaisePropertyChanged("p_request_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DesbloquearContrato", WrapperNamespace="http://pe/com/claro/siacpostpago/ws", IsWrapped=true)]
    public partial class DesbloquearContratoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com/SIACPostpago/DesbloqueaContrato.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com/SIACPostpago/DesbloqueaContrato.xsd")]
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_DesbloqueaContratoRequest bscs_DesbloqueaContratoRequest;
        
        public DesbloquearContratoRequest() {
        }
        
        public DesbloquearContratoRequest(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_DesbloqueaContratoRequest bscs_DesbloqueaContratoRequest) {
            this.bscs_DesbloqueaContratoRequest = bscs_DesbloqueaContratoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DesbloquearContratoResponse", WrapperNamespace="http://pe/com/claro/siacpostpago/ws", IsWrapped=true)]
    public partial class DesbloquearContratoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com/SIACPostpago/DesbloqueaContratoResponse.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com/SIACPostpago/DesbloqueaContratoResponse.xsd")]
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_DesbloqueaContratoResponse bscs_DesbloqueaContratoResponse;
        
        public DesbloquearContratoResponse() {
        }
        
        public DesbloquearContratoResponse(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_DesbloqueaContratoResponse bscs_DesbloqueaContratoResponse) {
            this.bscs_DesbloqueaContratoResponse = bscs_DesbloqueaContratoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com/SIACPostpago/listarTriaciones")]
    public partial class listarTriacionesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorField;
        
        private listarTriaciones[] listarTriacionesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listarTriaciones", Order=1)]
        public listarTriaciones[] listarTriaciones {
            get {
                return this.listarTriacionesField;
            }
            set {
                this.listarTriacionesField = value;
                this.RaisePropertyChanged("listarTriaciones");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com/SIACPostpago/listarTriaciones")]
    public partial class listarTriaciones : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int flag_campaniaField;
        
        private string tipo_triacionField;
        
        private int trios_onField;
        
        private int porcentaje_onField;
        
        private int trios_offField;
        
        private int porcentaje_offField;
        
        private string flagField;
        
        private string cod_Tipo_TriacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int flag_campania {
            get {
                return this.flag_campaniaField;
            }
            set {
                this.flag_campaniaField = value;
                this.RaisePropertyChanged("flag_campania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string tipo_triacion {
            get {
                return this.tipo_triacionField;
            }
            set {
                this.tipo_triacionField = value;
                this.RaisePropertyChanged("tipo_triacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int trios_on {
            get {
                return this.trios_onField;
            }
            set {
                this.trios_onField = value;
                this.RaisePropertyChanged("trios_on");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int porcentaje_on {
            get {
                return this.porcentaje_onField;
            }
            set {
                this.porcentaje_onField = value;
                this.RaisePropertyChanged("porcentaje_on");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int trios_off {
            get {
                return this.trios_offField;
            }
            set {
                this.trios_offField = value;
                this.RaisePropertyChanged("trios_off");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int porcentaje_off {
            get {
                return this.porcentaje_offField;
            }
            set {
                this.porcentaje_offField = value;
                this.RaisePropertyChanged("porcentaje_off");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Cod_Tipo_Triacion {
            get {
                return this.cod_Tipo_TriacionField;
            }
            set {
                this.cod_Tipo_TriacionField = value;
                this.RaisePropertyChanged("Cod_Tipo_Triacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTriaciones", WrapperNamespace="http://pe/com/claro/siacpostpago/ws", IsWrapped=true)]
    public partial class listarTriacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pe/com/claro/siacpostpago/ws", Order=0)]
        public string p_coid;
        
        public listarTriacionesRequest() {
        }
        
        public listarTriacionesRequest(string p_coid) {
            this.p_coid = p_coid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTriacionesResponse", WrapperNamespace="http://pe/com/claro/siacpostpago/ws", IsWrapped=true)]
    public partial class listarTriacionesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com/SIACPostpago/listarTriaciones", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com/SIACPostpago/listarTriaciones")]
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTriacionesResponse listarTriacionesResponse;
        
        public listarTriacionesResponse1() {
        }
        
        public listarTriacionesResponse1(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTriacionesResponse listarTriacionesResponse) {
            this.listarTriacionesResponse = listarTriacionesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com/SIACPostpago/bscs_cambioNombreRequest.xsd")]
    public partial class bscs_cambioNombreRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int p_CustomerIDField;
        
        private string p_EmailField;
        
        private string p_RazonSocialField;
        
        private string p_NombresField;
        
        private string p_ApellidoField;
        
        private string p_dnirucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int p_CustomerID {
            get {
                return this.p_CustomerIDField;
            }
            set {
                this.p_CustomerIDField = value;
                this.RaisePropertyChanged("p_CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string p_Email {
            get {
                return this.p_EmailField;
            }
            set {
                this.p_EmailField = value;
                this.RaisePropertyChanged("p_Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string p_RazonSocial {
            get {
                return this.p_RazonSocialField;
            }
            set {
                this.p_RazonSocialField = value;
                this.RaisePropertyChanged("p_RazonSocial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string p_Nombres {
            get {
                return this.p_NombresField;
            }
            set {
                this.p_NombresField = value;
                this.RaisePropertyChanged("p_Nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string p_Apellido {
            get {
                return this.p_ApellidoField;
            }
            set {
                this.p_ApellidoField = value;
                this.RaisePropertyChanged("p_Apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string p_dniruc {
            get {
                return this.p_dnirucField;
            }
            set {
                this.p_dnirucField = value;
                this.RaisePropertyChanged("p_dniruc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com/SIACPostpago/bscs_cambioNombreResponse.xsd")]
    public partial class bscs_cambioNombreResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int p_returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int p_return {
            get {
                return this.p_returnField;
            }
            set {
                this.p_returnField = value;
                this.RaisePropertyChanged("p_return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cambioNombre", WrapperNamespace="http://pe/com/claro/siacpostpago/ws", IsWrapped=true)]
    public partial class cambioNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com/SIACPostpago/bscs_cambioNombreRequest.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com/SIACPostpago/bscs_cambioNombreRequest.xsd")]
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioNombreRequest bscs_cambioNombreRequest;
        
        public cambioNombreRequest() {
        }
        
        public cambioNombreRequest(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioNombreRequest bscs_cambioNombreRequest) {
            this.bscs_cambioNombreRequest = bscs_cambioNombreRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cambioNombreResponse", WrapperNamespace="http://pe/com/claro/siacpostpago/ws", IsWrapped=true)]
    public partial class cambioNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com/SIACPostpago/bscs_cambioNombreResponse.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com/SIACPostpago/bscs_cambioNombreResponse.xsd")]
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioNombreResponse bscs_cambioNombreResponse;
        
        public cambioNombreResponse() {
        }
        
        public cambioNombreResponse(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioNombreResponse bscs_cambioNombreResponse) {
            this.bscs_cambioNombreResponse = bscs_cambioNombreResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com/SIACPostpago/BloqueaContratoRequest")]
    public partial class BloqueaContratoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int p_co_idField;
        
        private string p_tickler_codeField;
        
        private string p_tickler_desField;
        
        private string p_usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int p_co_id {
            get {
                return this.p_co_idField;
            }
            set {
                this.p_co_idField = value;
                this.RaisePropertyChanged("p_co_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string p_tickler_code {
            get {
                return this.p_tickler_codeField;
            }
            set {
                this.p_tickler_codeField = value;
                this.RaisePropertyChanged("p_tickler_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string p_tickler_des {
            get {
                return this.p_tickler_desField;
            }
            set {
                this.p_tickler_desField = value;
                this.RaisePropertyChanged("p_tickler_des");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string p_username {
            get {
                return this.p_usernameField;
            }
            set {
                this.p_usernameField = value;
                this.RaisePropertyChanged("p_username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com/SIACPostpago/BloqueaContratoResponse")]
    public partial class BloqueaContratoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int respuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("respuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BloquearContrato", WrapperNamespace="http://pe/com/claro/siacpostpago/ws", IsWrapped=true)]
    public partial class BloquearContratoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com/SIACPostpago/BloqueaContratoRequest", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com/SIACPostpago/BloqueaContratoRequest")]
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloqueaContratoRequest BloqueaContratoRequest;
        
        public BloquearContratoRequest() {
        }
        
        public BloquearContratoRequest(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloqueaContratoRequest BloqueaContratoRequest) {
            this.BloqueaContratoRequest = BloqueaContratoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BloquearContratoResponse", WrapperNamespace="http://pe/com/claro/siacpostpago/ws", IsWrapped=true)]
    public partial class BloquearContratoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com/SIACPostpago/BloqueaContratoResponse", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com/SIACPostpago/BloqueaContratoResponse")]
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloqueaContratoResponse BloqueaContratoResponse;
        
        public BloquearContratoResponse() {
        }
        
        public BloquearContratoResponse(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloqueaContratoResponse BloqueaContratoResponse) {
            this.BloqueaContratoResponse = BloqueaContratoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com/SIACPostpago/activaTriacion")]
    public partial class activaTriacionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string respuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("respuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActivaTriacion", WrapperNamespace="http://pe/com/claro/siacpostpago/ws", IsWrapped=true)]
    public partial class ActivaTriacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pe/com/claro/siacpostpago/ws", Order=0)]
        public string p_coid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pe/com/claro/siacpostpago/ws", Order=1)]
        public string p_trama;
        
        public ActivaTriacionRequest() {
        }
        
        public ActivaTriacionRequest(string p_coid, string p_trama) {
            this.p_coid = p_coid;
            this.p_trama = p_trama;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActivaTriacionResponse", WrapperNamespace="http://pe/com/claro/siacpostpago/ws", IsWrapped=true)]
    public partial class ActivaTriacionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com/SIACPostpago/activaTriacion", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com/SIACPostpago/activaTriacion")]
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.activaTriacionResponse activaTriacionResponse;
        
        public ActivaTriacionResponse1() {
        }
        
        public ActivaTriacionResponse1(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.activaTriacionResponse activaTriacionResponse) {
            this.activaTriacionResponse = activaTriacionResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com/SIACPostpago/bscs_cambioDatosMenoresRequest.xsd")]
    public partial class bscs_cambioDatosMenoresRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int p_CustomerIDField;
        
        private string p_cargoField;
        
        private string p_telefonoField;
        
        private string p_celularField;
        
        private string p_faxField;
        
        private string p_emailField;
        
        private string p_nombrecomercialField;
        
        private string p_contactoclienteField;
        
        private System.DateTime p_fechanacimientoField;
        
        private bool p_fechanacimientoFieldSpecified;
        
        private System.Nullable<int> p_nacionalidadField;
        
        private bool p_nacionalidadFieldSpecified;
        
        private string p_sexoField;
        
        private System.Nullable<int> p_estadocivilField;
        
        public bscs_cambioDatosMenoresRequest() {
            this.p_estadocivilField = -1;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int p_CustomerID {
            get {
                return this.p_CustomerIDField;
            }
            set {
                this.p_CustomerIDField = value;
                this.RaisePropertyChanged("p_CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string p_cargo {
            get {
                return this.p_cargoField;
            }
            set {
                this.p_cargoField = value;
                this.RaisePropertyChanged("p_cargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string p_telefono {
            get {
                return this.p_telefonoField;
            }
            set {
                this.p_telefonoField = value;
                this.RaisePropertyChanged("p_telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string p_celular {
            get {
                return this.p_celularField;
            }
            set {
                this.p_celularField = value;
                this.RaisePropertyChanged("p_celular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string p_fax {
            get {
                return this.p_faxField;
            }
            set {
                this.p_faxField = value;
                this.RaisePropertyChanged("p_fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string p_email {
            get {
                return this.p_emailField;
            }
            set {
                this.p_emailField = value;
                this.RaisePropertyChanged("p_email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string p_nombrecomercial {
            get {
                return this.p_nombrecomercialField;
            }
            set {
                this.p_nombrecomercialField = value;
                this.RaisePropertyChanged("p_nombrecomercial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string p_contactocliente {
            get {
                return this.p_contactoclienteField;
            }
            set {
                this.p_contactoclienteField = value;
                this.RaisePropertyChanged("p_contactocliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime p_fechanacimiento {
            get {
                return this.p_fechanacimientoField;
            }
            set {
                this.p_fechanacimientoField = value;
                this.RaisePropertyChanged("p_fechanacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool p_fechanacimientoSpecified {
            get {
                return this.p_fechanacimientoFieldSpecified;
            }
            set {
                this.p_fechanacimientoFieldSpecified = value;
                this.RaisePropertyChanged("p_fechanacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> p_nacionalidad {
            get {
                return this.p_nacionalidadField;
            }
            set {
                this.p_nacionalidadField = value;
                this.RaisePropertyChanged("p_nacionalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool p_nacionalidadSpecified {
            get {
                return this.p_nacionalidadFieldSpecified;
            }
            set {
                this.p_nacionalidadFieldSpecified = value;
                this.RaisePropertyChanged("p_nacionalidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string p_sexo {
            get {
                return this.p_sexoField;
            }
            set {
                this.p_sexoField = value;
                this.RaisePropertyChanged("p_sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public System.Nullable<int> p_estadocivil {
            get {
                return this.p_estadocivilField;
            }
            set {
                this.p_estadocivilField = value;
                this.RaisePropertyChanged("p_estadocivil");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com/SIACPostpago/bscs_cambioDatosMenoresResponse.xsd")]
    public partial class bscs_cambioDatosMenoresResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int p_ResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int P_Result {
            get {
                return this.p_ResultField;
            }
            set {
                this.p_ResultField = value;
                this.RaisePropertyChanged("P_Result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizaDatosMenores", WrapperNamespace="http://pe/com/claro/siacpostpago/ws", IsWrapped=true)]
    public partial class actualizaDatosMenoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com/SIACPostpago/bscs_cambioDatosMenoresRequest.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com/SIACPostpago/bscs_cambioDatosMenoresRequest.xsd")]
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioDatosMenoresRequest bscs_cambioDatosMenoresRequest;
        
        public actualizaDatosMenoresRequest() {
        }
        
        public actualizaDatosMenoresRequest(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioDatosMenoresRequest bscs_cambioDatosMenoresRequest) {
            this.bscs_cambioDatosMenoresRequest = bscs_cambioDatosMenoresRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizaDatosMenoresResponse", WrapperNamespace="http://pe/com/claro/siacpostpago/ws", IsWrapped=true)]
    public partial class actualizaDatosMenoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com/SIACPostpago/bscs_cambioDatosMenoresResponse.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com/SIACPostpago/bscs_cambioDatosMenoresResponse.xsd")]
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioDatosMenoresResponse bscs_cambioDatosMenoresResponse;
        
        public actualizaDatosMenoresResponse() {
        }
        
        public actualizaDatosMenoresResponse(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioDatosMenoresResponse bscs_cambioDatosMenoresResponse) {
            this.bscs_cambioDatosMenoresResponse = bscs_cambioDatosMenoresResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EjecutaTriacion", WrapperNamespace="http://pe/com/claro/siacpostpago/ws", IsWrapped=true)]
    public partial class EjecutaTriacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pe/com/claro/siacpostpago/ws", Order=0)]
        public string p_dn_num;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pe/com/claro/siacpostpago/ws", Order=1)]
        public int p_fideliza;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pe/com/claro/siacpostpago/ws", Order=2)]
        public string p_cod_trim;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pe/com/claro/siacpostpago/ws", Order=3)]
        public string p_trama;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pe/com/claro/siacpostpago/ws", Order=4)]
        public string p_accion;
        
        public EjecutaTriacionRequest() {
        }
        
        public EjecutaTriacionRequest(string p_dn_num, int p_fideliza, string p_cod_trim, string p_trama, string p_accion) {
            this.p_dn_num = p_dn_num;
            this.p_fideliza = p_fideliza;
            this.p_cod_trim = p_cod_trim;
            this.p_trama = p_trama;
            this.p_accion = p_accion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EjecutaTriacionResponse", WrapperNamespace="http://pe/com/claro/siacpostpago/ws", IsWrapped=true)]
    public partial class EjecutaTriacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com/SIACPostpago/activaTriacion", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com/SIACPostpago/activaTriacion")]
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.activaTriacionResponse activaTriacionResponse;
        
        public EjecutaTriacionResponse() {
        }
        
        public EjecutaTriacionResponse(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.activaTriacionResponse activaTriacionResponse) {
            this.activaTriacionResponse = activaTriacionResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com/SIACPostpago/listarTicklers")]
    public partial class listarTicklersResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultadoField;
        
        private listarTicklers[] listarTicklersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("resultado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listarTicklers", Order=1)]
        public listarTicklers[] listarTicklers {
            get {
                return this.listarTicklersField;
            }
            set {
                this.listarTicklersField = value;
                this.RaisePropertyChanged("listarTicklers");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com/SIACPostpago/listarTicklers")]
    public partial class listarTicklers : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int tickler_numberField;
        
        private System.DateTime created_dateField;
        
        private string created_byField;
        
        private string tickler_codeField;
        
        private string tickler_statusField;
        
        private string long_descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int tickler_number {
            get {
                return this.tickler_numberField;
            }
            set {
                this.tickler_numberField = value;
                this.RaisePropertyChanged("tickler_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime created_date {
            get {
                return this.created_dateField;
            }
            set {
                this.created_dateField = value;
                this.RaisePropertyChanged("created_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string created_by {
            get {
                return this.created_byField;
            }
            set {
                this.created_byField = value;
                this.RaisePropertyChanged("created_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string tickler_code {
            get {
                return this.tickler_codeField;
            }
            set {
                this.tickler_codeField = value;
                this.RaisePropertyChanged("tickler_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string tickler_status {
            get {
                return this.tickler_statusField;
            }
            set {
                this.tickler_statusField = value;
                this.RaisePropertyChanged("tickler_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string long_description {
            get {
                return this.long_descriptionField;
            }
            set {
                this.long_descriptionField = value;
                this.RaisePropertyChanged("long_description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTicklers", WrapperNamespace="http://pe/com/claro/siacpostpago/ws", IsWrapped=true)]
    public partial class listarTicklersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pe/com/claro/siacpostpago/ws", Order=0)]
        public string p_coid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pe/com/claro/siacpostpago/ws", Order=1)]
        public string p_trama;
        
        public listarTicklersRequest() {
        }
        
        public listarTicklersRequest(string p_coid, string p_trama) {
            this.p_coid = p_coid;
            this.p_trama = p_trama;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTicklersResponse", WrapperNamespace="http://pe/com/claro/siacpostpago/ws", IsWrapped=true)]
    public partial class listarTicklersResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com/SIACPostpago/listarTicklers", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com/SIACPostpago/listarTicklers")]
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTicklersResponse listarTicklersResponse;
        
        public listarTicklersResponse1() {
        }
        
        public listarTicklersResponse1(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTicklersResponse listarTicklersResponse) {
            this.listarTicklersResponse = listarTicklersResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com/SIACPostpago/bscs_cambioDireccionPostal_request.xsd")]
    public partial class bscs_cambioDireccionPostal_request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int p_CustomerIDField;
        
        private string p_DireccionField;
        
        private string p_NotasDireccionField;
        
        private string p_DistritoField;
        
        private string p_ProvinciaField;
        
        private string p_CodigoPostalField;
        
        private string p_DepartamentoField;
        
        private string p_PaisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int p_CustomerID {
            get {
                return this.p_CustomerIDField;
            }
            set {
                this.p_CustomerIDField = value;
                this.RaisePropertyChanged("p_CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string p_Direccion {
            get {
                return this.p_DireccionField;
            }
            set {
                this.p_DireccionField = value;
                this.RaisePropertyChanged("p_Direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string p_NotasDireccion {
            get {
                return this.p_NotasDireccionField;
            }
            set {
                this.p_NotasDireccionField = value;
                this.RaisePropertyChanged("p_NotasDireccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string p_Distrito {
            get {
                return this.p_DistritoField;
            }
            set {
                this.p_DistritoField = value;
                this.RaisePropertyChanged("p_Distrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string p_Provincia {
            get {
                return this.p_ProvinciaField;
            }
            set {
                this.p_ProvinciaField = value;
                this.RaisePropertyChanged("p_Provincia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string p_CodigoPostal {
            get {
                return this.p_CodigoPostalField;
            }
            set {
                this.p_CodigoPostalField = value;
                this.RaisePropertyChanged("p_CodigoPostal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string p_Departamento {
            get {
                return this.p_DepartamentoField;
            }
            set {
                this.p_DepartamentoField = value;
                this.RaisePropertyChanged("p_Departamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string p_Pais {
            get {
                return this.p_PaisField;
            }
            set {
                this.p_PaisField = value;
                this.RaisePropertyChanged("p_Pais");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com/SIACPostpago/bscs_cambioDireccionPostal_response.xsd")]
    public partial class bscs_cambioDireccionPostal_response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int p_resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int p_result {
            get {
                return this.p_resultField;
            }
            set {
                this.p_resultField = value;
                this.RaisePropertyChanged("p_result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cambioDireccionPostal", WrapperNamespace="http://pe/com/claro/siacpostpago/ws", IsWrapped=true)]
    public partial class cambioDireccionPostalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com/SIACPostpago/bscs_cambioDireccionPostal_request.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com/SIACPostpago/bscs_cambioDireccionPostal_request.xsd")]
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioDireccionPostal_request bscs_cambioDireccionPostal_request;
        
        public cambioDireccionPostalRequest() {
        }
        
        public cambioDireccionPostalRequest(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioDireccionPostal_request bscs_cambioDireccionPostal_request) {
            this.bscs_cambioDireccionPostal_request = bscs_cambioDireccionPostal_request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cambioDireccionPostalResponse", WrapperNamespace="http://pe/com/claro/siacpostpago/ws", IsWrapped=true)]
    public partial class cambioDireccionPostalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com/SIACPostpago/bscs_cambioDireccionPostal_response.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com/SIACPostpago/bscs_cambioDireccionPostal_response.xsd")]
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioDireccionPostal_response bscs_cambioDireccionPostal_response;
        
        public cambioDireccionPostalResponse() {
        }
        
        public cambioDireccionPostalResponse(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioDireccionPostal_response bscs_cambioDireccionPostal_response) {
            this.bscs_cambioDireccionPostal_response = bscs_cambioDireccionPostal_response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SIACPostpagoTxWSChannel : Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SIACPostpagoTxWSClient : System.ServiceModel.ClientBase<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS>, Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS {
        
        public SIACPostpagoTxWSClient() {
        }
        
        public SIACPostpagoTxWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SIACPostpagoTxWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SIACPostpagoTxWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SIACPostpagoTxWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.DesbloquearContratoResponse Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS.DesbloquearContrato(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.DesbloquearContratoRequest request) {
            return base.Channel.DesbloquearContrato(request);
        }
        
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_DesbloqueaContratoResponse DesbloquearContrato(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_DesbloqueaContratoRequest bscs_DesbloqueaContratoRequest) {
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.DesbloquearContratoRequest inValue = new Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.DesbloquearContratoRequest();
            inValue.bscs_DesbloqueaContratoRequest = bscs_DesbloqueaContratoRequest;
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.DesbloquearContratoResponse retVal = ((Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS)(this)).DesbloquearContrato(inValue);
            return retVal.bscs_DesbloqueaContratoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.DesbloquearContratoResponse> Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS.DesbloquearContratoAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.DesbloquearContratoRequest request) {
            return base.Channel.DesbloquearContratoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.DesbloquearContratoResponse> DesbloquearContratoAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_DesbloqueaContratoRequest bscs_DesbloqueaContratoRequest) {
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.DesbloquearContratoRequest inValue = new Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.DesbloquearContratoRequest();
            inValue.bscs_DesbloqueaContratoRequest = bscs_DesbloqueaContratoRequest;
            return ((Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS)(this)).DesbloquearContratoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTriacionesResponse1 Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS.listarTriaciones(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTriacionesRequest request) {
            return base.Channel.listarTriaciones(request);
        }
        
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTriacionesResponse listarTriaciones(string p_coid) {
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTriacionesRequest inValue = new Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTriacionesRequest();
            inValue.p_coid = p_coid;
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTriacionesResponse1 retVal = ((Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS)(this)).listarTriaciones(inValue);
            return retVal.listarTriacionesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTriacionesResponse1> Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS.listarTriacionesAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTriacionesRequest request) {
            return base.Channel.listarTriacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTriacionesResponse1> listarTriacionesAsync(string p_coid) {
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTriacionesRequest inValue = new Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTriacionesRequest();
            inValue.p_coid = p_coid;
            return ((Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS)(this)).listarTriacionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioNombreResponse Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS.cambioNombre(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioNombreRequest request) {
            return base.Channel.cambioNombre(request);
        }
        
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioNombreResponse cambioNombre(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioNombreRequest bscs_cambioNombreRequest) {
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioNombreRequest inValue = new Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioNombreRequest();
            inValue.bscs_cambioNombreRequest = bscs_cambioNombreRequest;
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioNombreResponse retVal = ((Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS)(this)).cambioNombre(inValue);
            return retVal.bscs_cambioNombreResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioNombreResponse> Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS.cambioNombreAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioNombreRequest request) {
            return base.Channel.cambioNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioNombreResponse> cambioNombreAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioNombreRequest bscs_cambioNombreRequest) {
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioNombreRequest inValue = new Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioNombreRequest();
            inValue.bscs_cambioNombreRequest = bscs_cambioNombreRequest;
            return ((Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS)(this)).cambioNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloquearContratoResponse Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS.BloquearContrato(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloquearContratoRequest request) {
            return base.Channel.BloquearContrato(request);
        }
        
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloqueaContratoResponse BloquearContrato(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloqueaContratoRequest BloqueaContratoRequest) {
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloquearContratoRequest inValue = new Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloquearContratoRequest();
            inValue.BloqueaContratoRequest = BloqueaContratoRequest;
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloquearContratoResponse retVal = ((Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS)(this)).BloquearContrato(inValue);
            return retVal.BloqueaContratoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloquearContratoResponse> Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS.BloquearContratoAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloquearContratoRequest request) {
            return base.Channel.BloquearContratoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloquearContratoResponse> BloquearContratoAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloqueaContratoRequest BloqueaContratoRequest) {
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloquearContratoRequest inValue = new Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.BloquearContratoRequest();
            inValue.BloqueaContratoRequest = BloqueaContratoRequest;
            return ((Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS)(this)).BloquearContratoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.ActivaTriacionResponse1 Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS.ActivaTriacion(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.ActivaTriacionRequest request) {
            return base.Channel.ActivaTriacion(request);
        }
        
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.activaTriacionResponse ActivaTriacion(string p_coid, string p_trama) {
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.ActivaTriacionRequest inValue = new Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.ActivaTriacionRequest();
            inValue.p_coid = p_coid;
            inValue.p_trama = p_trama;
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.ActivaTriacionResponse1 retVal = ((Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS)(this)).ActivaTriacion(inValue);
            return retVal.activaTriacionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.ActivaTriacionResponse1> Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS.ActivaTriacionAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.ActivaTriacionRequest request) {
            return base.Channel.ActivaTriacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.ActivaTriacionResponse1> ActivaTriacionAsync(string p_coid, string p_trama) {
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.ActivaTriacionRequest inValue = new Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.ActivaTriacionRequest();
            inValue.p_coid = p_coid;
            inValue.p_trama = p_trama;
            return ((Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS)(this)).ActivaTriacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.actualizaDatosMenoresResponse Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS.actualizaDatosMenores(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.actualizaDatosMenoresRequest request) {
            return base.Channel.actualizaDatosMenores(request);
        }
        
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioDatosMenoresResponse actualizaDatosMenores(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioDatosMenoresRequest bscs_cambioDatosMenoresRequest) {
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.actualizaDatosMenoresRequest inValue = new Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.actualizaDatosMenoresRequest();
            inValue.bscs_cambioDatosMenoresRequest = bscs_cambioDatosMenoresRequest;
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.actualizaDatosMenoresResponse retVal = ((Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS)(this)).actualizaDatosMenores(inValue);
            return retVal.bscs_cambioDatosMenoresResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.actualizaDatosMenoresResponse> Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS.actualizaDatosMenoresAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.actualizaDatosMenoresRequest request) {
            return base.Channel.actualizaDatosMenoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.actualizaDatosMenoresResponse> actualizaDatosMenoresAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioDatosMenoresRequest bscs_cambioDatosMenoresRequest) {
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.actualizaDatosMenoresRequest inValue = new Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.actualizaDatosMenoresRequest();
            inValue.bscs_cambioDatosMenoresRequest = bscs_cambioDatosMenoresRequest;
            return ((Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS)(this)).actualizaDatosMenoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.EjecutaTriacionResponse Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS.EjecutaTriacion(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.EjecutaTriacionRequest request) {
            return base.Channel.EjecutaTriacion(request);
        }
        
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.activaTriacionResponse EjecutaTriacion(string p_dn_num, int p_fideliza, string p_cod_trim, string p_trama, string p_accion) {
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.EjecutaTriacionRequest inValue = new Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.EjecutaTriacionRequest();
            inValue.p_dn_num = p_dn_num;
            inValue.p_fideliza = p_fideliza;
            inValue.p_cod_trim = p_cod_trim;
            inValue.p_trama = p_trama;
            inValue.p_accion = p_accion;
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.EjecutaTriacionResponse retVal = ((Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS)(this)).EjecutaTriacion(inValue);
            return retVal.activaTriacionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.EjecutaTriacionResponse> Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS.EjecutaTriacionAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.EjecutaTriacionRequest request) {
            return base.Channel.EjecutaTriacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.EjecutaTriacionResponse> EjecutaTriacionAsync(string p_dn_num, int p_fideliza, string p_cod_trim, string p_trama, string p_accion) {
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.EjecutaTriacionRequest inValue = new Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.EjecutaTriacionRequest();
            inValue.p_dn_num = p_dn_num;
            inValue.p_fideliza = p_fideliza;
            inValue.p_cod_trim = p_cod_trim;
            inValue.p_trama = p_trama;
            inValue.p_accion = p_accion;
            return ((Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS)(this)).EjecutaTriacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTicklersResponse1 Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS.listarTicklers(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTicklersRequest request) {
            return base.Channel.listarTicklers(request);
        }
        
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTicklersResponse listarTicklers(string p_coid, string p_trama) {
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTicklersRequest inValue = new Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTicklersRequest();
            inValue.p_coid = p_coid;
            inValue.p_trama = p_trama;
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTicklersResponse1 retVal = ((Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS)(this)).listarTicklers(inValue);
            return retVal.listarTicklersResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTicklersResponse1> Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS.listarTicklersAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTicklersRequest request) {
            return base.Channel.listarTicklersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTicklersResponse1> listarTicklersAsync(string p_coid, string p_trama) {
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTicklersRequest inValue = new Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.listarTicklersRequest();
            inValue.p_coid = p_coid;
            inValue.p_trama = p_trama;
            return ((Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS)(this)).listarTicklersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioDireccionPostalResponse Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS.cambioDireccionPostal(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioDireccionPostalRequest request) {
            return base.Channel.cambioDireccionPostal(request);
        }
        
        public Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioDireccionPostal_response cambioDireccionPostal(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioDireccionPostal_request bscs_cambioDireccionPostal_request) {
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioDireccionPostalRequest inValue = new Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioDireccionPostalRequest();
            inValue.bscs_cambioDireccionPostal_request = bscs_cambioDireccionPostal_request;
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioDireccionPostalResponse retVal = ((Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS)(this)).cambioDireccionPostal(inValue);
            return retVal.bscs_cambioDireccionPostal_response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioDireccionPostalResponse> Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS.cambioDireccionPostalAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioDireccionPostalRequest request) {
            return base.Channel.cambioDireccionPostalAsync(request);
        }
        
        public System.Threading.Tasks.Task<Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioDireccionPostalResponse> cambioDireccionPostalAsync(Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.bscs_cambioDireccionPostal_request bscs_cambioDireccionPostal_request) {
            Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioDireccionPostalRequest inValue = new Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.cambioDireccionPostalRequest();
            inValue.bscs_cambioDireccionPostal_request = bscs_cambioDireccionPostal_request;
            return ((Claro.SIACU.ProxyService.IFI.SIACU.TriacionPostpagoWS.SIACPostpagoTxWS)(this)).cambioDireccionPostalAsync(inValue);
        }
    }
}
