//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Claro.SIACU.ProxyService.IFI.WSBRMS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RULEAPPAUTOMREGLASAUTOMATIZACIONDEDOCUMENTOSBinding", Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
        "ENTOS")]
    public partial class REGLASAUTOMATIZACIONDEDOCUMENTOSDecisionService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback REGLASAUTOMATIZACIONDEDOCUMENTOSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public REGLASAUTOMATIZACIONDEDOCUMENTOSDecisionService() {
            this.Url = global::Claro.SIACU.ProxyService.IFI.Properties.Settings.Default.Claro_SIACU_ProxyService_IFI_WSBRMS_REGLASAUTOMATIZACIONDEDOCUMENTOSDecisionService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event REGLASAUTOMATIZACIONDEDOCUMENTOSCompletedEventHandler REGLASAUTOMATIZACIONDEDOCUMENTOSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("REGLASAUTOMATIZACIONDEDOCUMENTOS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("REGLASAUTOMATIZACIONDEDOCUMENTOSResponse", Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
            "ENTOS")]
        public REGLASAUTOMATIZACIONDEDOCUMENTOSResponse REGLASAUTOMATIZACIONDEDOCUMENTOS([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
            "ENTOS")] REGLASAUTOMATIZACIONDEDOCUMENTOSRequest REGLASAUTOMATIZACIONDEDOCUMENTOSRequest) {
            object[] results = this.Invoke("REGLASAUTOMATIZACIONDEDOCUMENTOS", new object[] {
                        REGLASAUTOMATIZACIONDEDOCUMENTOSRequest});
            return ((REGLASAUTOMATIZACIONDEDOCUMENTOSResponse)(results[0]));
        }
        
        /// <remarks/>
        public void REGLASAUTOMATIZACIONDEDOCUMENTOSAsync(REGLASAUTOMATIZACIONDEDOCUMENTOSRequest REGLASAUTOMATIZACIONDEDOCUMENTOSRequest) {
            this.REGLASAUTOMATIZACIONDEDOCUMENTOSAsync(REGLASAUTOMATIZACIONDEDOCUMENTOSRequest, null);
        }
        
        /// <remarks/>
        public void REGLASAUTOMATIZACIONDEDOCUMENTOSAsync(REGLASAUTOMATIZACIONDEDOCUMENTOSRequest REGLASAUTOMATIZACIONDEDOCUMENTOSRequest, object userState) {
            if ((this.REGLASAUTOMATIZACIONDEDOCUMENTOSOperationCompleted == null)) {
                this.REGLASAUTOMATIZACIONDEDOCUMENTOSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnREGLASAUTOMATIZACIONDEDOCUMENTOSOperationCompleted);
            }
            this.InvokeAsync("REGLASAUTOMATIZACIONDEDOCUMENTOS", new object[] {
                        REGLASAUTOMATIZACIONDEDOCUMENTOSRequest}, this.REGLASAUTOMATIZACIONDEDOCUMENTOSOperationCompleted, userState);
        }
        
        private void OnREGLASAUTOMATIZACIONDEDOCUMENTOSOperationCompleted(object arg) {
            if ((this.REGLASAUTOMATIZACIONDEDOCUMENTOSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.REGLASAUTOMATIZACIONDEDOCUMENTOSCompleted(this, new REGLASAUTOMATIZACIONDEDOCUMENTOSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
        "ENTOS")]
    public partial class REGLASAUTOMATIZACIONDEDOCUMENTOSRequest {
        
        private string decisionIDField;
        
        private pedidoEspecifico pedidoEspecificoField;
        
        private pedidoGeneral pedidoGeneralField;
        
        /// <comentarios/>
        public string DecisionID {
            get {
                return this.decisionIDField;
            }
            set {
                this.decisionIDField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
            "ENTOS/param")]
        public pedidoEspecifico pedidoEspecifico {
            get {
                return this.pedidoEspecificoField;
            }
            set {
                this.pedidoEspecificoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
            "ENTOS/param")]
        public pedidoGeneral pedidoGeneral {
            get {
                return this.pedidoGeneralField;
            }
            set {
                this.pedidoGeneralField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
        "ENTOS/param")]
    public partial class pedidoEspecifico {
        
        private consulta[] pedidoEspecifico1Field;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute("pedidoEspecifico", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public consulta[] pedidoEspecifico1 {
            get {
                return this.pedidoEspecifico1Field;
            }
            set {
                this.pedidoEspecifico1Field = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
        "ENTOS")]
    public partial class consulta {
        
        private acuerdo acuerdoField;
        
        private string identificadorField;
        
        private producto productoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public acuerdo acuerdo {
            get {
                return this.acuerdoField;
            }
            set {
                this.acuerdoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
        "ENTOS")]
    public partial class acuerdo {
        
        private int antiguedadField;
        
        private bool antiguedadFieldSpecified;
        
        private int cuotasField;
        
        private bool cuotasFieldSpecified;
        
        private string equipoField;
        
        private string flagEquipoField;
        
        private string plazoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int antiguedad {
            get {
                return this.antiguedadField;
            }
            set {
                this.antiguedadField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool antiguedadSpecified {
            get {
                return this.antiguedadFieldSpecified;
            }
            set {
                this.antiguedadFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cuotas {
            get {
                return this.cuotasField;
            }
            set {
                this.cuotasField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cuotasSpecified {
            get {
                return this.cuotasFieldSpecified;
            }
            set {
                this.cuotasFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equipo {
            get {
                return this.equipoField;
            }
            set {
                this.equipoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string flagEquipo {
            get {
                return this.flagEquipoField;
            }
            set {
                this.flagEquipoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string plazo {
            get {
                return this.plazoField;
            }
            set {
                this.plazoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
        "ENTOS")]
    public partial class resultado {
        
        private string archivoField;
        
        private string identificadorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string archivo {
            get {
                return this.archivoField;
            }
            set {
                this.archivoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
        "ENTOS")]
    public partial class proceso {
        
        private string canalField;
        
        private string despachoField;
        
        private System.DateTime fechaEjecucionField;
        
        private bool fechaEjecucionFieldSpecified;
        
        private int horaEjecucionField;
        
        private bool horaEjecucionFieldSpecified;
        
        private string operacionField;
        
        private string sistemaField;
        
        private string tipoDeOperacionField;
        
        private string transaccionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string despacho {
            get {
                return this.despachoField;
            }
            set {
                this.despachoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaEjecucion {
            get {
                return this.fechaEjecucionField;
            }
            set {
                this.fechaEjecucionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEjecucionSpecified {
            get {
                return this.fechaEjecucionFieldSpecified;
            }
            set {
                this.fechaEjecucionFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int horaEjecucion {
            get {
                return this.horaEjecucionField;
            }
            set {
                this.horaEjecucionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool horaEjecucionSpecified {
            get {
                return this.horaEjecucionFieldSpecified;
            }
            set {
                this.horaEjecucionFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operacion {
            get {
                return this.operacionField;
            }
            set {
                this.operacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sistema {
            get {
                return this.sistemaField;
            }
            set {
                this.sistemaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDeOperacion {
            get {
                return this.tipoDeOperacionField;
            }
            set {
                this.tipoDeOperacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
        "ENTOS")]
    public partial class cliente {
        
        private string documentoField;
        
        private int permanenciaField;
        
        private bool permanenciaFieldSpecified;
        
        private tipoSiNo planCartaField;
        
        private bool planCartaFieldSpecified;
        
        private tipoSiNo reciboElectronicoField;
        
        private bool reciboElectronicoFieldSpecified;
        
        private tipoSiNo rentaAdelantadaField;
        
        private bool rentaAdelantadaFieldSpecified;
        
        private string segmentoField;
        
        private string tipoDeClienteField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int permanencia {
            get {
                return this.permanenciaField;
            }
            set {
                this.permanenciaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool permanenciaSpecified {
            get {
                return this.permanenciaFieldSpecified;
            }
            set {
                this.permanenciaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoSiNo planCarta {
            get {
                return this.planCartaField;
            }
            set {
                this.planCartaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool planCartaSpecified {
            get {
                return this.planCartaFieldSpecified;
            }
            set {
                this.planCartaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoSiNo reciboElectronico {
            get {
                return this.reciboElectronicoField;
            }
            set {
                this.reciboElectronicoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reciboElectronicoSpecified {
            get {
                return this.reciboElectronicoFieldSpecified;
            }
            set {
                this.reciboElectronicoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoSiNo rentaAdelantada {
            get {
                return this.rentaAdelantadaField;
            }
            set {
                this.rentaAdelantadaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rentaAdelantadaSpecified {
            get {
                return this.rentaAdelantadaFieldSpecified;
            }
            set {
                this.rentaAdelantadaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string segmento {
            get {
                return this.segmentoField;
            }
            set {
                this.segmentoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDeCliente {
            get {
                return this.tipoDeClienteField;
            }
            set {
                this.tipoDeClienteField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
        "ENTOS")]
    public enum tipoSiNo {
        
        /// <comentarios/>
        SI,
        
        /// <comentarios/>
        NO,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="pedidoGeneral", Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
        "ENTOS")]
    public partial class pedidoGeneral1 {
        
        private cliente clienteField;
        
        private proceso procesoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public proceso proceso {
            get {
                return this.procesoField;
            }
            set {
                this.procesoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
        "ENTOS")]
    public partial class producto {
        
        private string campanaField;
        
        private string estadoDelServicioField;
        
        private string faseField;
        
        private string grupoDelPlanField;
        
        private string paqueteField;
        
        private string planField;
        
        private tipoSiNo proteccionMovilField;
        
        private bool proteccionMovilFieldSpecified;
        
        private string retencionField;
        
        private string servicioField;
        
        private string tipoDeProductoField;
        
        private string topeDeConsumoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string campana {
            get {
                return this.campanaField;
            }
            set {
                this.campanaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estadoDelServicio {
            get {
                return this.estadoDelServicioField;
            }
            set {
                this.estadoDelServicioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fase {
            get {
                return this.faseField;
            }
            set {
                this.faseField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string grupoDelPlan {
            get {
                return this.grupoDelPlanField;
            }
            set {
                this.grupoDelPlanField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string paquete {
            get {
                return this.paqueteField;
            }
            set {
                this.paqueteField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string plan {
            get {
                return this.planField;
            }
            set {
                this.planField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoSiNo proteccionMovil {
            get {
                return this.proteccionMovilField;
            }
            set {
                this.proteccionMovilField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool proteccionMovilSpecified {
            get {
                return this.proteccionMovilFieldSpecified;
            }
            set {
                this.proteccionMovilFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string retencion {
            get {
                return this.retencionField;
            }
            set {
                this.retencionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDeProducto {
            get {
                return this.tipoDeProductoField;
            }
            set {
                this.tipoDeProductoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string topeDeConsumo {
            get {
                return this.topeDeConsumoField;
            }
            set {
                this.topeDeConsumoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
        "ENTOS/param")]
    public partial class pedidoGeneral {
        
        private pedidoGeneral1 pedidoGeneral1Field;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("pedidoGeneral", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pedidoGeneral1 pedidoGeneral1 {
            get {
                return this.pedidoGeneral1Field;
            }
            set {
                this.pedidoGeneral1Field = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
        "ENTOS")]
    public partial class REGLASAUTOMATIZACIONDEDOCUMENTOSResponse {
        
        private string decisionIDField;
        
        private listaEspecifica listaEspecificaField;
        
        private listaGeneral listaGeneralField;
        
        /// <comentarios/>
        public string DecisionID {
            get {
                return this.decisionIDField;
            }
            set {
                this.decisionIDField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
            "ENTOS/param")]
        public listaEspecifica listaEspecifica {
            get {
                return this.listaEspecificaField;
            }
            set {
                this.listaEspecificaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
            "ENTOS/param")]
        public listaGeneral listaGeneral {
            get {
                return this.listaGeneralField;
            }
            set {
                this.listaGeneralField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
        "ENTOS/param")]
    public partial class listaEspecifica {
        
        private resultado[] listaEspecifica1Field;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute("listaEspecifica", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public resultado[] listaEspecifica1 {
            get {
                return this.listaEspecifica1Field;
            }
            set {
                this.listaEspecifica1Field = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/rules/decisionservice/RULEAPPAUTOM/REGLASAUTOMATIZACIONDEDOCUM" +
        "ENTOS/param")]
    public partial class listaGeneral {
        
        private string[] listaGeneral1Field;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute("listaGeneral", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("documento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] listaGeneral1 {
            get {
                return this.listaGeneral1Field;
            }
            set {
                this.listaGeneral1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    public delegate void REGLASAUTOMATIZACIONDEDOCUMENTOSCompletedEventHandler(object sender, REGLASAUTOMATIZACIONDEDOCUMENTOSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class REGLASAUTOMATIZACIONDEDOCUMENTOSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal REGLASAUTOMATIZACIONDEDOCUMENTOSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public REGLASAUTOMATIZACIONDEDOCUMENTOSResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((REGLASAUTOMATIZACIONDEDOCUMENTOSResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591