using CommonSeviceModels = Claro.SIACU.Web.WebApplication.IFI.CommonIFIService;
using FolderModel = Claro.SIACU.Web.WebApplication.IFI.Areas.IFITransactions.Models;

using AutoMapper;

namespace Claro.SIACU.Web.WebApplication.IFI.Mappings
{
    public class ViewModelToServiceModelMappings
    {
        public static void Configure(IMapperConfigurationExpression config)
        {
            config.CreateMap<FolderModel.InteractionModel, CommonSeviceModels.Interaction>()
            .ForMember(s => s.OBJID_CONTACTO, o => o.MapFrom(d => d.ObjidContacto))
            .ForMember(s => s.OBJID_SITE, o => o.MapFrom(d => d.ObjidSite))
            .ForMember(s => s.CUENTA, o => o.MapFrom(d => d.Cuenta))
            .ForMember(s => s.ID_INTERACCION, o => o.MapFrom(d => d.IdInteractio))
            .ForMember(s => s.FECHA_CREACION, o => o.MapFrom(d => d.DateCreaction))
            .ForMember(s => s.TELEFONO, o => o.MapFrom(d => d.Telephone))
            .ForMember(s => s.TIPO, o => o.MapFrom(d => d.Type))
            .ForMember(s => s.CLASE, o => o.MapFrom(d => d.Class))
            .ForMember(s => s.SUBCLASE, o => o.MapFrom(d => d.SubClass))
            .ForMember(s => s.TIPIFICACION, o => o.MapFrom(d => d.Tipification))
            .ForMember(s => s.TIPO_CODIGO, o => o.MapFrom(d => d.TypeCode))
            .ForMember(s => s.CLASE_CODIGO, o => o.MapFrom(d => d.ClassCode))
            .ForMember(s => s.SUBCLASE_CODIGO, o => o.MapFrom(d => d.SubClassCode))
            .ForMember(s => s.INSERTADO_POR, o => o.MapFrom(d => d.InsertPor))
            .ForMember(s => s.TIPO_INTER, o => o.MapFrom(d => d.TypeInter))
            .ForMember(s => s.METODO, o => o.MapFrom(d => d.Method))
            .ForMember(s => s.RESULTADO, o => o.MapFrom(d => d.Result))
            .ForMember(s => s.HECHO_EN_UNO, o => o.MapFrom(d => d.MadeOne))
            .ForMember(s => s.AGENTE, o => o.MapFrom(d => d.Agenth))
            .ForMember(s => s.NOMBRE_AGENTE, o => o.MapFrom(d => d.NameAgenth))
            .ForMember(s => s.APELLIDO_AGENTE, o => o.MapFrom(d => d.ApellidoAgenth))
            .ForMember(s => s.ID_CASO, o => o.MapFrom(d => d.IdCase))
            .ForMember(s => s.NOTAS, o => o.MapFrom(d => d.Note))
            .ForMember(s => s.FLAG_CASO, o => o.MapFrom(d => d.FlagCase))
            .ForMember(s => s.USUARIO_PROCESO, o => o.MapFrom(d => d.UserProces))
            .ForMember(s => s.SERVICIO, o => o.MapFrom(d => d.Service))
            .ForMember(s => s.INCONVENIENTE, o => o.MapFrom(d => d.Inconveniente))
            .ForMember(s => s.SERVICIO_CODE, o => o.MapFrom(d => d.ServiceCode))
            .ForMember(s => s.INCONVENIENTE_CODE, o => o.MapFrom(d => d.InconvenienteCode))
            .ForMember(s => s.CONTRATO, o => o.MapFrom(d => d.Contract))
            .ForMember(s => s.PLANO, o => o.MapFrom(d => d.Plan))
            .ForMember(s => s.VALOR_1, o => o.MapFrom(d => d.Value1))
            .ForMember(s => s.VALOR_2, o => o.MapFrom(d => d.Value2));

            config.CreateMap<FolderModel.InteractionModel, CommonSeviceModels.Iteraction>()
                .ForMember(s => s.OBJID_CONTACTO, o => o.MapFrom(d => d.ObjidContacto))
                .ForMember(s => s.OBJID_SITE, o => o.MapFrom(d => d.ObjidSite))
                .ForMember(s => s.CUENTA, o => o.MapFrom(d => d.Cuenta))
                .ForMember(s => s.ID_INTERACCION, o => o.MapFrom(d => d.IdInteractio))
                .ForMember(s => s.FECHA_CREACION, o => o.MapFrom(d => d.DateCreaction))
                .ForMember(s => s.TELEFONO, o => o.MapFrom(d => d.Telephone))
                .ForMember(s => s.TIPO, o => o.MapFrom(d => d.Type))
                .ForMember(s => s.CLASE, o => o.MapFrom(d => d.Class))
                .ForMember(s => s.SUBCLASE, o => o.MapFrom(d => d.SubClass))
                .ForMember(s => s.TIPIFICACION, o => o.MapFrom(d => d.Tipification))
                .ForMember(s => s.TIPO_CODIGO, o => o.MapFrom(d => d.TypeCode))
                .ForMember(s => s.CLASE_CODIGO, o => o.MapFrom(d => d.ClassCode))
                .ForMember(s => s.SUBCLASE_CODIGO, o => o.MapFrom(d => d.SubClassCode))
                .ForMember(s => s.INSERTADO_POR, o => o.MapFrom(d => d.InsertPor))
                .ForMember(s => s.TIPO_INTER, o => o.MapFrom(d => d.TypeInter))
                .ForMember(s => s.METODO, o => o.MapFrom(d => d.Method))
                .ForMember(s => s.RESULTADO, o => o.MapFrom(d => d.Result))
                .ForMember(s => s.HECHO_EN_UNO, o => o.MapFrom(d => d.MadeOne))
                .ForMember(s => s.AGENTE, o => o.MapFrom(d => d.Agenth))
                .ForMember(s => s.NOMBRE_AGENTE, o => o.MapFrom(d => d.NameAgenth))
                .ForMember(s => s.APELLIDO_AGENTE, o => o.MapFrom(d => d.ApellidoAgenth))
                .ForMember(s => s.ID_CASO, o => o.MapFrom(d => d.IdCase))
                .ForMember(s => s.NOTAS, o => o.MapFrom(d => d.Note))
                .ForMember(s => s.FLAG_CASO, o => o.MapFrom(d => d.FlagCase))
                .ForMember(s => s.USUARIO_PROCESO, o => o.MapFrom(d => d.UserProces))
                .ForMember(s => s.SERVICIO, o => o.MapFrom(d => d.Service))
                .ForMember(s => s.INCONVENIENTE, o => o.MapFrom(d => d.Inconveniente))
                .ForMember(s => s.SERVICIO, o => o.MapFrom(d => d.ServiceCode));

            //Insertar Plantilla de Interaccion
            config.CreateMap<FolderModel.TemplateInteractionModel, CommonSeviceModels.InsertTemplateInteraction>()
                .ForMember(s => s._NOMBRE_TRANSACCION, o => o.MapFrom(d => d.NOMBRE_TRANSACCION))
                .ForMember(s => s._X_NRO_INTERACCION, o => o.MapFrom(d => d.X_NRO_INTERACCION))
                .ForMember(s => s._X_INTER_1, o => o.MapFrom(d => d.X_INTER_1))
                .ForMember(s => s._X_INTER_2, o => o.MapFrom(d => d.X_INTER_2))
                .ForMember(s => s._X_INTER_3, o => o.MapFrom(d => d.X_INTER_3))
                .ForMember(s => s._X_INTER_4, o => o.MapFrom(d => d.X_INTER_4))
                .ForMember(s => s._X_INTER_5, o => o.MapFrom(d => d.X_INTER_5))
                .ForMember(s => s._X_INTER_6, o => o.MapFrom(d => d.X_INTER_6))
                .ForMember(s => s._X_INTER_7, o => o.MapFrom(d => d.X_INTER_7))
                .ForMember(s => s._X_INTER_8, o => o.MapFrom(d => d.X_INTER_8))
                .ForMember(s => s._X_INTER_9, o => o.MapFrom(d => d.X_INTER_9))
                .ForMember(s => s._X_INTER_10, o => o.MapFrom(d => d.X_INTER_10))
                .ForMember(s => s._X_INTER_11, o => o.MapFrom(d => d.X_INTER_11))
                .ForMember(s => s._X_INTER_12, o => o.MapFrom(d => d.X_INTER_12))
                .ForMember(s => s._X_INTER_13, o => o.MapFrom(d => d.X_INTER_13))
                .ForMember(s => s._X_INTER_14, o => o.MapFrom(d => d.X_INTER_14))
                .ForMember(s => s._X_INTER_15, o => o.MapFrom(d => d.X_INTER_15))
                .ForMember(s => s._X_INTER_16, o => o.MapFrom(d => d.X_INTER_16))
                .ForMember(s => s._X_INTER_17, o => o.MapFrom(d => d.X_INTER_17))
                .ForMember(s => s._X_INTER_18, o => o.MapFrom(d => d.X_INTER_18))
                .ForMember(s => s._X_INTER_19, o => o.MapFrom(d => d.X_INTER_19))
                .ForMember(s => s._X_INTER_20, o => o.MapFrom(d => d.X_INTER_20))
                .ForMember(s => s._X_INTER_21, o => o.MapFrom(d => d.X_INTER_21))
                .ForMember(s => s._X_INTER_22, o => o.MapFrom(d => d.X_INTER_22))
                .ForMember(s => s._X_INTER_23, o => o.MapFrom(d => d.X_INTER_23))
                .ForMember(s => s._X_INTER_24, o => o.MapFrom(d => d.X_INTER_24))
                .ForMember(s => s._X_INTER_25, o => o.MapFrom(d => d.X_INTER_25))
                .ForMember(s => s._X_INTER_26, o => o.MapFrom(d => d.X_INTER_26))
                .ForMember(s => s._X_INTER_27, o => o.MapFrom(d => d.X_INTER_27))
                .ForMember(s => s._X_INTER_28, o => o.MapFrom(d => d.X_INTER_28))
                .ForMember(s => s._X_INTER_29, o => o.MapFrom(d => d.X_INTER_29))
                .ForMember(s => s._X_INTER_30, o => o.MapFrom(d => d.X_INTER_30))
                .ForMember(s => s._X_PLUS_INTER2INTERACT, o => o.MapFrom(d => d.X_PLUS_INTER2INTERACT))
                .ForMember(s => s._X_ADJUSTMENT_AMOUNT, o => o.MapFrom(d => d.X_ADJUSTMENT_AMOUNT))
                .ForMember(s => s._X_ADJUSTMENT_REASON, o => o.MapFrom(d => d.X_ADJUSTMENT_REASON))
                .ForMember(s => s._X_ADDRESS, o => o.MapFrom(d => d.X_ADDRESS))
                .ForMember(s => s._X_AMOUNT_UNIT, o => o.MapFrom(d => d.X_AMOUNT_UNIT))
                .ForMember(s => s._X_BIRTHDAY, o => o.MapFrom(d => d.X_BIRTHDAY))
                .ForMember(s => s._X_CLARIFY_INTERACTION, o => o.MapFrom(d => d.X_CLARIFY_INTERACTION))
                .ForMember(s => s._X_CLARO_LDN1, o => o.MapFrom(d => d.X_CLARO_LDN1))
                .ForMember(s => s._X_CLARO_LDN2, o => o.MapFrom(d => d.X_CLARO_LDN2))
                .ForMember(s => s._X_CLARO_LDN3, o => o.MapFrom(d => d.X_CLARO_LDN3))
                .ForMember(s => s._X_CLARO_LDN4, o => o.MapFrom(d => d.X_CLARO_LDN4))
                .ForMember(s => s._X_CLAROLOCAL1, o => o.MapFrom(d => d.X_CLAROLOCAL1))
                .ForMember(s => s._X_CLAROLOCAL2, o => o.MapFrom(d => d.X_CLAROLOCAL2))
                .ForMember(s => s._X_CLAROLOCAL3, o => o.MapFrom(d => d.X_CLAROLOCAL3))
                .ForMember(s => s._X_CLAROLOCAL4, o => o.MapFrom(d => d.X_CLAROLOCAL4))
                .ForMember(s => s._X_CLAROLOCAL5, o => o.MapFrom(d => d.X_CLAROLOCAL5))
                .ForMember(s => s._X_CLAROLOCAL6, o => o.MapFrom(d => d.X_CLAROLOCAL6))
                .ForMember(s => s._X_CONTACT_PHONE, o => o.MapFrom(d => d.X_CONTACT_PHONE))
                .ForMember(s => s._X_DNI_LEGAL_REP, o => o.MapFrom(d => d.X_DNI_LEGAL_REP))
                .ForMember(s => s._X_DOCUMENT_NUMBER, o => o.MapFrom(d => d.X_DOCUMENT_NUMBER))
                .ForMember(s => s._X_EMAIL, o => o.MapFrom(d => d.X_EMAIL))
                .ForMember(s => s._X_FIRST_NAME, o => o.MapFrom(d => d.X_FIRST_NAME))
                .ForMember(s => s._X_FIXED_NUMBER, o => o.MapFrom(d => d.X_FIXED_NUMBER))
                .ForMember(s => s._X_FLAG_CHANGE_USER, o => o.MapFrom(d => d.X_FLAG_CHANGE_USER))
                .ForMember(s => s._X_FLAG_LEGAL_REP, o => o.MapFrom(d => d.X_FLAG_LEGAL_REP))
                .ForMember(s => s._X_FLAG_OTHER, o => o.MapFrom(d => d.X_FLAG_OTHER))
                .ForMember(s => s._X_FLAG_TITULAR, o => o.MapFrom(d => d.X_FLAG_TITULAR))
                .ForMember(s => s._X_IMEI, o => o.MapFrom(d => d.X_IMEI))
                .ForMember(s => s._X_LAST_NAME, o => o.MapFrom(d => d.X_LAST_NAME))
                .ForMember(s => s._X_LASTNAME_REP, o => o.MapFrom(d => d.X_LASTNAME_REP))
                .ForMember(s => s._X_LDI_NUMBER, o => o.MapFrom(d => d.X_LDI_NUMBER))
                .ForMember(s => s._X_NAME_LEGAL_REP, o => o.MapFrom(d => d.X_NAME_LEGAL_REP))
                .ForMember(s => s._X_OLD_CLARO_LDN1, o => o.MapFrom(d => d.X_OLD_CLARO_LDN1))
                .ForMember(s => s._X_OLD_CLARO_LDN2, o => o.MapFrom(d => d.X_OLD_CLARO_LDN2))
                .ForMember(s => s._X_OLD_CLARO_LDN3, o => o.MapFrom(d => d.X_OLD_CLARO_LDN3))
                .ForMember(s => s._X_OLD_CLARO_LDN4, o => o.MapFrom(d => d.X_OLD_CLARO_LDN4))
                .ForMember(s => s._X_OLD_CLAROLOCAL1, o => o.MapFrom(d => d.X_OLD_CLAROLOCAL1))
                .ForMember(s => s._X_OLD_CLAROLOCAL2, o => o.MapFrom(d => d.X_OLD_CLAROLOCAL2))
                .ForMember(s => s._X_OLD_CLAROLOCAL3, o => o.MapFrom(d => d.X_OLD_CLAROLOCAL3))
                .ForMember(s => s._X_OLD_CLAROLOCAL4, o => o.MapFrom(d => d.X_OLD_CLAROLOCAL4))
                .ForMember(s => s._X_OLD_CLAROLOCAL5, o => o.MapFrom(d => d.X_OLD_CLAROLOCAL5))
                .ForMember(s => s._X_OLD_CLAROLOCAL6, o => o.MapFrom(d => d.X_OLD_CLAROLOCAL6))
                .ForMember(s => s._X_OLD_DOC_NUMBER, o => o.MapFrom(d => d.X_OLD_DOC_NUMBER))
                .ForMember(s => s._X_OLD_FIRST_NAME, o => o.MapFrom(d => d.X_OLD_FIRST_NAME))
                .ForMember(s => s._X_OLD_FIXED_PHONE, o => o.MapFrom(d => d.X_OLD_FIXED_PHONE))
                .ForMember(s => s._X_OLD_LAST_NAME, o => o.MapFrom(d => d.X_OLD_LAST_NAME))
                .ForMember(s => s._X_OLD_LDI_NUMBER, o => o.MapFrom(d => d.X_OLD_LDI_NUMBER))
                .ForMember(s => s._X_OLD_FIXED_NUMBER, o => o.MapFrom(d => d.X_OLD_FIXED_NUMBER))
                .ForMember(s => s._X_OPERATION_TYPE, o => o.MapFrom(d => d.X_OPERATION_TYPE))
                .ForMember(s => s._X_OTHER_DOC_NUMBER, o => o.MapFrom(d => d.X_OTHER_DOC_NUMBER))
                .ForMember(s => s._X_OTHER_FIRST_NAME, o => o.MapFrom(d => d.X_OTHER_FIRST_NAME))
                .ForMember(s => s._X_OTHER_LAST_NAME, o => o.MapFrom(d => d.X_OTHER_LAST_NAME))
                .ForMember(s => s._X_OTHER_PHONE, o => o.MapFrom(d => d.X_OTHER_PHONE))
                .ForMember(s => s._X_PHONE_LEGAL_REP, o => o.MapFrom(d => d.X_PHONE_LEGAL_REP))
                .ForMember(s => s._X_REFERENCE_PHONE, o => o.MapFrom(d => d.X_REFERENCE_PHONE))
                .ForMember(s => s._X_REASON, o => o.MapFrom(d => d.X_REASON))
                .ForMember(s => s._X_MODEL, o => o.MapFrom(d => d.X_MODEL))
                .ForMember(s => s._X_LOT_CODE, o => o.MapFrom(d => d.X_LOT_CODE))
                .ForMember(s => s._X_FLAG_REGISTERED, o => o.MapFrom(d => d.X_FLAG_REGISTERED))
                .ForMember(s => s._X_REGISTRATION_REASON, o => o.MapFrom(d => d.X_REGISTRATION_REASON))
                .ForMember(s => s._X_CLARO_NUMBER, o => o.MapFrom(d => d.X_CLARO_NUMBER))
                .ForMember(s => s._X_MONTH, o => o.MapFrom(d => d.X_MONTH))
                .ForMember(s => s._X_OST_NUMBER, o => o.MapFrom(d => d.X_OST_NUMBER))
                .ForMember(s => s._X_BASKET, o => o.MapFrom(d => d.X_BASKET))
                .ForMember(s => s._X_RECHARGE_DATE, o => o.MapFrom(d => d.X_RECHARGE_DATE))
                .ForMember(s => s._X_EXPIRE_DATE, o => o.MapFrom(d => d.X_EXPIRE_DATE))
                .ForMember(s => s._ID_INTERACCION, o => o.MapFrom(d => d.ID_INTERACCION))
                .ForMember(s => s._Script_IMEI, o => o.MapFrom(d => d.Script_IMEI))
                .ForMember(s => s._SESSION_ID, o => o.MapFrom(d => d.SESSION_ID))
                .ForMember(s => s._MSISDN, o => o.MapFrom(d => d.MSISDN))
                .ForMember(s => s._P_OLD_ID_CONTACTO, o => o.MapFrom(d => d.P_OLD_ID_CONTACTO))
                .ForMember(s => s._P_USUARIO_ID, o => o.MapFrom(d => d.P_USUARIO_ID))
                .ForMember(s => s._TIENE_DATOS, o => o.MapFrom(d => d.TIENE_DATOS))
                .ForMember(s => s._TICKET, o => o.MapFrom(d => d.TICKET))
                .ForMember(s => s._ACCION, o => o.MapFrom(d => d.ACCION))
                .ForMember(s => s._NRO_DIAS, o => o.MapFrom(d => d.NRO_DIAS))
                .ForMember(s => s._NRO_TELEFONO, o => o.MapFrom(d => d.NRO_TELEFONO))
                .ForMember(s => s._NRO_TARJETA, o => o.MapFrom(d => d.NRO_TARJETA))
                .ForMember(s => s._X_ADDRESS5, o => o.MapFrom(d => d.X_ADDRESS5))
                .ForMember(s => s._X_CHARGE_AMOUNT, o => o.MapFrom(d => d.X_CHARGE_AMOUNT))
                .ForMember(s => s._X_CITY, o => o.MapFrom(d => d.X_CITY))
                .ForMember(s => s._X_CONTACT_SEX, o => o.MapFrom(d => d.X_CONTACT_SEX))
                .ForMember(s => s._X_DEPARTMENT, o => o.MapFrom(d => d.X_DEPARTMENT))
                .ForMember(s => s._X_DISTRICT, o => o.MapFrom(d => d.X_DISTRICT))
                .ForMember(s => s._X_EMAIL_CONFIRMATION, o => o.MapFrom(d => d.X_EMAIL_CONFIRMATION))
                .ForMember(s => s._X_FAX, o => o.MapFrom(d => d.X_FAX))
                .ForMember(s => s._X_FLAG_CHARGE, o => o.MapFrom(d => d.X_FLAG_CHARGE))
                .ForMember(s => s._X_MARITAL_STATUS, o => o.MapFrom(d => d.X_MARITAL_STATUS))
                .ForMember(s => s._X_OCCUPATION, o => o.MapFrom(d => d.X_OCCUPATION))
                .ForMember(s => s._X_POSITION, o => o.MapFrom(d => d.X_POSITION))
                .ForMember(s => s._X_REFERENCE_ADDRESS, o => o.MapFrom(d => d.X_REFERENCE_ADDRESS))
                .ForMember(s => s._X_TYPE_DOCUMENT, o => o.MapFrom(d => d.X_TYPE_DOCUMENT))
                .ForMember(s => s._X_ZIPCODE, o => o.MapFrom(d => d.X_ZIPCODE))
                .ForMember(s => s._X_ICCID, o => o.MapFrom(d => d.X_ICCID))
                .ForMember(s => s._X_TRIO_ANTIGUO, o => o.MapFrom(d => d.X_TRIO_ANTIGUO));


        }
    }
}