//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Claro.SIACU.ProxyService.IFI.ServiciosPostpagoWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosPostPagoWSServiceSoapBinding", Namespace="http://pe/com/claro/esb/services/serviciospostpago/ws")]
    public partial class ServiciosPostPagoWSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback consultaServicioEstadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback serviciosContratoOperationCompleted;
        
        private System.Threading.SendOrPostCallback contratosTelefonoOperationCompleted;
        
        private System.Threading.SendOrPostCallback registraServicioComercialOperationCompleted;
        
        private System.Threading.SendOrPostCallback serviciosBSCSServComercialOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosPostPagoWSService() {
            this.Url = global::Claro.SIACU.ProxyService.IFI.Properties.Settings.Default.Claro_SIACU_ProxyService_IFI_ServiciosPostpagoWS_ServiciosPostPagoWSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultaServicioEstadoCompletedEventHandler consultaServicioEstadoCompleted;
        
        /// <remarks/>
        public event serviciosContratoCompletedEventHandler serviciosContratoCompleted;
        
        /// <remarks/>
        public event contratosTelefonoCompletedEventHandler contratosTelefonoCompleted;
        
        /// <remarks/>
        public event registraServicioComercialCompletedEventHandler registraServicioComercialCompleted;
        
        /// <remarks/>
        public event serviciosBSCSServComercialCompletedEventHandler serviciosBSCSServComercialCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/esb/services/serviciospostpago/ws", ResponseNamespace="http://pe/com/claro/esb/services/serviciospostpago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultaServicioEstadoResponse", Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")]
        public consultaServicioEstadoResponse consultaServicioEstado([System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")] consultaServicioEstadoRequest consultaServicioEstadoRequest) {
            object[] results = this.Invoke("consultaServicioEstado", new object[] {
                        consultaServicioEstadoRequest});
            return ((consultaServicioEstadoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void consultaServicioEstadoAsync(consultaServicioEstadoRequest consultaServicioEstadoRequest) {
            this.consultaServicioEstadoAsync(consultaServicioEstadoRequest, null);
        }
        
        /// <remarks/>
        public void consultaServicioEstadoAsync(consultaServicioEstadoRequest consultaServicioEstadoRequest, object userState) {
            if ((this.consultaServicioEstadoOperationCompleted == null)) {
                this.consultaServicioEstadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaServicioEstadoOperationCompleted);
            }
            this.InvokeAsync("consultaServicioEstado", new object[] {
                        consultaServicioEstadoRequest}, this.consultaServicioEstadoOperationCompleted, userState);
        }
        
        private void OnconsultaServicioEstadoOperationCompleted(object arg) {
            if ((this.consultaServicioEstadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaServicioEstadoCompleted(this, new consultaServicioEstadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/esb/services/serviciospostpago/ws", ResponseNamespace="http://pe/com/claro/esb/services/serviciospostpago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("serviciosContratoResponse", Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")]
        public serviciosContratoResponse serviciosContrato([System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")] serviciosContratoRequest serviciosContratoRequest) {
            object[] results = this.Invoke("serviciosContrato", new object[] {
                        serviciosContratoRequest});
            return ((serviciosContratoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void serviciosContratoAsync(serviciosContratoRequest serviciosContratoRequest) {
            this.serviciosContratoAsync(serviciosContratoRequest, null);
        }
        
        /// <remarks/>
        public void serviciosContratoAsync(serviciosContratoRequest serviciosContratoRequest, object userState) {
            if ((this.serviciosContratoOperationCompleted == null)) {
                this.serviciosContratoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnserviciosContratoOperationCompleted);
            }
            this.InvokeAsync("serviciosContrato", new object[] {
                        serviciosContratoRequest}, this.serviciosContratoOperationCompleted, userState);
        }
        
        private void OnserviciosContratoOperationCompleted(object arg) {
            if ((this.serviciosContratoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.serviciosContratoCompleted(this, new serviciosContratoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/esb/services/serviciospostpago/ws", ResponseNamespace="http://pe/com/claro/esb/services/serviciospostpago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("contratosTelefonoResponse", Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")]
        public contratosTelefonoResponse contratosTelefono([System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")] contratosTelefonoRequest contratosTelefonoRequest) {
            object[] results = this.Invoke("contratosTelefono", new object[] {
                        contratosTelefonoRequest});
            return ((contratosTelefonoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void contratosTelefonoAsync(contratosTelefonoRequest contratosTelefonoRequest) {
            this.contratosTelefonoAsync(contratosTelefonoRequest, null);
        }
        
        /// <remarks/>
        public void contratosTelefonoAsync(contratosTelefonoRequest contratosTelefonoRequest, object userState) {
            if ((this.contratosTelefonoOperationCompleted == null)) {
                this.contratosTelefonoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncontratosTelefonoOperationCompleted);
            }
            this.InvokeAsync("contratosTelefono", new object[] {
                        contratosTelefonoRequest}, this.contratosTelefonoOperationCompleted, userState);
        }
        
        private void OncontratosTelefonoOperationCompleted(object arg) {
            if ((this.contratosTelefonoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.contratosTelefonoCompleted(this, new contratosTelefonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/esb/services/serviciospostpago/ws", ResponseNamespace="http://pe/com/claro/esb/services/serviciospostpago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("registraServicioComercialResponse", Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")]
        public registraServicioComercialResponse registraServicioComercial([System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")] registraServicioComercialRequest registraServicioComercialRequest) {
            object[] results = this.Invoke("registraServicioComercial", new object[] {
                        registraServicioComercialRequest});
            return ((registraServicioComercialResponse)(results[0]));
        }
        
        /// <remarks/>
        public void registraServicioComercialAsync(registraServicioComercialRequest registraServicioComercialRequest) {
            this.registraServicioComercialAsync(registraServicioComercialRequest, null);
        }
        
        /// <remarks/>
        public void registraServicioComercialAsync(registraServicioComercialRequest registraServicioComercialRequest, object userState) {
            if ((this.registraServicioComercialOperationCompleted == null)) {
                this.registraServicioComercialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistraServicioComercialOperationCompleted);
            }
            this.InvokeAsync("registraServicioComercial", new object[] {
                        registraServicioComercialRequest}, this.registraServicioComercialOperationCompleted, userState);
        }
        
        private void OnregistraServicioComercialOperationCompleted(object arg) {
            if ((this.registraServicioComercialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registraServicioComercialCompleted(this, new registraServicioComercialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/esb/services/serviciospostpago/ws", ResponseNamespace="http://pe/com/claro/esb/services/serviciospostpago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("serviciosBSCSServComercialResponse", Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")]
        public serviciosBSCSServComercialResponse serviciosBSCSServComercial([System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")] serviciosBSCSServComercialRequest serviciosBSCSServComercialRequest) {
            object[] results = this.Invoke("serviciosBSCSServComercial", new object[] {
                        serviciosBSCSServComercialRequest});
            return ((serviciosBSCSServComercialResponse)(results[0]));
        }
        
        /// <remarks/>
        public void serviciosBSCSServComercialAsync(serviciosBSCSServComercialRequest serviciosBSCSServComercialRequest) {
            this.serviciosBSCSServComercialAsync(serviciosBSCSServComercialRequest, null);
        }
        
        /// <remarks/>
        public void serviciosBSCSServComercialAsync(serviciosBSCSServComercialRequest serviciosBSCSServComercialRequest, object userState) {
            if ((this.serviciosBSCSServComercialOperationCompleted == null)) {
                this.serviciosBSCSServComercialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnserviciosBSCSServComercialOperationCompleted);
            }
            this.InvokeAsync("serviciosBSCSServComercial", new object[] {
                        serviciosBSCSServComercialRequest}, this.serviciosBSCSServComercialOperationCompleted, userState);
        }
        
        private void OnserviciosBSCSServComercialOperationCompleted(object arg) {
            if ((this.serviciosBSCSServComercialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.serviciosBSCSServComercialCompleted(this, new serviciosBSCSServComercialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")]
    public partial class consultaServicioEstadoRequest {
        
        private string loginField;
        
        private string sistemaField;
        
        private string coIdField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sistema {
            get {
                return this.sistemaField;
            }
            set {
                this.sistemaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coId {
            get {
                return this.coIdField;
            }
            set {
                this.coIdField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")]
    public partial class servicioBscs {
        
        private string servicioField;
        
        private string paqueteField;
        
        private string estadoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string paquete {
            get {
                return this.paqueteField;
            }
            set {
                this.paqueteField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")]
    public partial class contrato {
        
        private string custCodeField;
        
        private string nombreField;
        
        private string coIdField;
        
        private string estadoField;
        
        private string fechaField;
        
        private string razonField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string custCode {
            get {
                return this.custCodeField;
            }
            set {
                this.custCodeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coId {
            get {
                return this.coIdField;
            }
            set {
                this.coIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string razon {
            get {
                return this.razonField;
            }
            set {
                this.razonField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")]
    public partial class servicio {
        
        private string coGrpField;
        
        private string deGrpField;
        
        private string noGrpField;
        
        private string coSerField;
        
        private string deSerField;
        
        private string noSerField;
        
        private string coExclField;
        
        private string deExclField;
        
        private string estadoField;
        
        private string validoField;
        
        private string suscripField;
        
        private string cargoFijoField;
        
        private string cuotaField;
        
        private string finalField;
        
        private string periodField;
        
        private string bloqActField;
        
        private string bloqDesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coGrp {
            get {
                return this.coGrpField;
            }
            set {
                this.coGrpField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deGrp {
            get {
                return this.deGrpField;
            }
            set {
                this.deGrpField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string noGrp {
            get {
                return this.noGrpField;
            }
            set {
                this.noGrpField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coSer {
            get {
                return this.coSerField;
            }
            set {
                this.coSerField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deSer {
            get {
                return this.deSerField;
            }
            set {
                this.deSerField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string noSer {
            get {
                return this.noSerField;
            }
            set {
                this.noSerField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coExcl {
            get {
                return this.coExclField;
            }
            set {
                this.coExclField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deExcl {
            get {
                return this.deExclField;
            }
            set {
                this.deExclField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valido {
            get {
                return this.validoField;
            }
            set {
                this.validoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string suscrip {
            get {
                return this.suscripField;
            }
            set {
                this.suscripField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cargoFijo {
            get {
                return this.cargoFijoField;
            }
            set {
                this.cargoFijoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cuota {
            get {
                return this.cuotaField;
            }
            set {
                this.cuotaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string final {
            get {
                return this.finalField;
            }
            set {
                this.finalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BloqAct {
            get {
                return this.bloqActField;
            }
            set {
                this.bloqActField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BloqDes {
            get {
                return this.bloqDesField;
            }
            set {
                this.bloqDesField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")]
    public partial class consultaServicioEstadoResponse {
        
        private string tmDesField;
        
        private servicio[] servicioEstadoField;
        
        private string errNumField;
        
        private string errMsjField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tmDes {
            get {
                return this.tmDesField;
            }
            set {
                this.tmDesField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("servicioEstado", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public servicio[] servicioEstado {
            get {
                return this.servicioEstadoField;
            }
            set {
                this.servicioEstadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errNum {
            get {
                return this.errNumField;
            }
            set {
                this.errNumField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errMsj {
            get {
                return this.errMsjField;
            }
            set {
                this.errMsjField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")]
    public partial class serviciosContratoRequest {
        
        private string loginField;
        
        private string sistemaField;
        
        private string coIdField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sistema {
            get {
                return this.sistemaField;
            }
            set {
                this.sistemaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coId {
            get {
                return this.coIdField;
            }
            set {
                this.coIdField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")]
    public partial class serviciosContratoResponse {
        
        private string timDesField;
        
        private servicio[] servicioField;
        
        private string errNumField;
        
        private string errMsjField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timDes {
            get {
                return this.timDesField;
            }
            set {
                this.timDesField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("servicio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public servicio[] servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errNum {
            get {
                return this.errNumField;
            }
            set {
                this.errNumField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errMsj {
            get {
                return this.errMsjField;
            }
            set {
                this.errMsjField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")]
    public partial class contratosTelefonoRequest {
        
        private string loginField;
        
        private string sistemaField;
        
        private string msisdnField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sistema {
            get {
                return this.sistemaField;
            }
            set {
                this.sistemaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")]
    public partial class contratosTelefonoResponse {
        
        private contrato[] contratoField;
        
        private string errNumField;
        
        private string errMsjField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("contrato", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public contrato[] contrato {
            get {
                return this.contratoField;
            }
            set {
                this.contratoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errNum {
            get {
                return this.errNumField;
            }
            set {
                this.errNumField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errMsj {
            get {
                return this.errMsjField;
            }
            set {
                this.errMsjField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")]
    public partial class registraServicioComercialRequest {
        
        private string loginField;
        
        private string sistemaField;
        
        private string idTransaccionField;
        
        private string coIdField;
        
        private string coSerField;
        
        private string tipRegField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sistema {
            get {
                return this.sistemaField;
            }
            set {
                this.sistemaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coId {
            get {
                return this.coIdField;
            }
            set {
                this.coIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coSer {
            get {
                return this.coSerField;
            }
            set {
                this.coSerField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipReg {
            get {
                return this.tipRegField;
            }
            set {
                this.tipRegField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")]
    public partial class registraServicioComercialResponse {
        
        private string errNumField;
        
        private string errMsjField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errNum {
            get {
                return this.errNumField;
            }
            set {
                this.errNumField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errMsj {
            get {
                return this.errMsjField;
            }
            set {
                this.errMsjField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")]
    public partial class serviciosBSCSServComercialRequest {
        
        private string loginField;
        
        private string sistemaField;
        
        private string coSerField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sistema {
            get {
                return this.sistemaField;
            }
            set {
                this.sistemaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coSer {
            get {
                return this.coSerField;
            }
            set {
                this.coSerField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/serviciosPostPago/schemas/serviciosPostPago")]
    public partial class serviciosBSCSServComercialResponse {
        
        private string deSerField;
        
        private servicioBscs[] servicioBscsField;
        
        private string errNumField;
        
        private string errMsjField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deSer {
            get {
                return this.deSerField;
            }
            set {
                this.deSerField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("servicioBscs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public servicioBscs[] servicioBscs {
            get {
                return this.servicioBscsField;
            }
            set {
                this.servicioBscsField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errNum {
            get {
                return this.errNumField;
            }
            set {
                this.errNumField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errMsj {
            get {
                return this.errMsjField;
            }
            set {
                this.errMsjField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    public delegate void consultaServicioEstadoCompletedEventHandler(object sender, consultaServicioEstadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaServicioEstadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaServicioEstadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public consultaServicioEstadoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((consultaServicioEstadoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    public delegate void serviciosContratoCompletedEventHandler(object sender, serviciosContratoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class serviciosContratoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal serviciosContratoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public serviciosContratoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((serviciosContratoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    public delegate void contratosTelefonoCompletedEventHandler(object sender, contratosTelefonoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class contratosTelefonoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal contratosTelefonoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public contratosTelefonoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((contratosTelefonoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    public delegate void registraServicioComercialCompletedEventHandler(object sender, registraServicioComercialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registraServicioComercialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registraServicioComercialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public registraServicioComercialResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((registraServicioComercialResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    public delegate void serviciosBSCSServComercialCompletedEventHandler(object sender, serviciosBSCSServComercialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class serviciosBSCSServComercialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal serviciosBSCSServComercialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public serviciosBSCSServComercialResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((serviciosBSCSServComercialResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591