//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claro.SIACU.ProxyService.IFI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limdeseaiv25.tim.com.pe:8903/RegistroAuditoria/RegistroAuditoriaPortSB11")]
        public string Claro_SIACU_ProxyService_IFI_RegistroAuditoriaWS_RegistroAuditoriaService {
            get {
                return ((string)(this["Claro_SIACU_ProxyService_IFI_RegistroAuditoriaWS_RegistroAuditoriaService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limdeseaiv25.tim.com.pe:8903/ConsultaOpcionesAuditoria/ConsultaOpcionesAud" +
            "itoriaPortSB11")]
        public string Claro_SIACU_ProxyService_IFI_ConsultaOpcionesAuditoriaWS_ConsultaOpcionesAuditoriaService {
            get {
                return ((string)(this["Claro_SIACU_ProxyService_IFI_ConsultaOpcionesAuditoriaWS_ConsultaOpcionesAuditori" +
                    "aService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limdeseaiv22.tim.com.pe:8909/AuditoriaWS/EbsAuditoria")]
        public string Claro_SIACU_ProxyService_IFI_AuditoriaWS_EbsAuditoriaService {
            get {
                return ((string)(this["Claro_SIACU_ProxyService_IFI_AuditoriaWS_EbsAuditoriaService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limdeseaiv24.tim.com.pe:8909/ServiciosPostPagoWS/ServiciosPostPagoWS")]
        public string Claro_SIACU_ProxyService_IFI_ServiciosPostpagoWS_ServiciosPostPagoWSService {
            get {
                return ((string)(this["Claro_SIACU_ProxyService_IFI_ServiciosPostpagoWS_ServiciosPostPagoWSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.74.189:8901/EnvioCorreoSB/proxy_services/EnvioCorreoSB")]
        public string Claro_SIACU_ProxyService_IFI_SIACU_EnvioCorreoSB_EnvioCorreoSBPortTypeSOAP11BindingQSService {
            get {
                return ((string)(this["Claro_SIACU_ProxyService_IFI_SIACU_EnvioCorreoSB_EnvioCorreoSBPortTypeSOAP11Bindi" +
                    "ngQSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.74.223:8909/EngineService/EngineService")]
        public string Claro_SIACU_ProxyService_IFI_WSGeneratePDF_EngineService {
            get {
                return ((string)(this["Claro_SIACU_ProxyService_IFI_WSGeneratePDF_EngineService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://limdesosbv05.tim.com.pe:8909/Billing_Services/BSCS/Transaction/Transaccion" +
            "OCC")]
        public string Claro_SIACU_ProxyService_IFI_TransaccionOCC_TransaccionOCC {
            get {
                return ((string)(this["Claro_SIACU_ProxyService_IFI_TransaccionOCC_TransaccionOCC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://LIM-5S37KC2:8080/")]
        public string Claro_SIACU_ProxyService_IFI_WSBRMS_REGLASAUTOMATIZACIONDEDOCUMENTOSDecisionService {
            get {
                return ((string)(this["Claro_SIACU_ProxyService_IFI_WSBRMS_REGLASAUTOMATIZACIONDEDOCUMENTOSDecisionServi" +
                    "ce"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.17.26.51:21000/PRS_FirmaDigital/SRV_PRS_FirmaDigital/Service/Expositio" +
            "n/EXP_FirmaDigital")]
        public string Claro_SIACU_ProxyService_IFI_SIACU_DigitalSignature_PRS_FirmaDigital_WS {
            get {
                return ((string)(this["Claro_SIACU_ProxyService_IFI_SIACU_DigitalSignature_PRS_FirmaDigital_WS"]));
            }
        }
    }
}
